### ISSUE TITLE
Menu bar align-right

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#10]
Align the Menu bar to the right, to mimic http://eu-citizen.science/

- align right
- menu items in ALL CAPS
- Open Sans
-rename Documents to Resources

i.e>                                                                  HOME / PROJECTS / RESOURCES / ABOUT

**Comment by vvalvesga** [comment]
Resolved with 68d16600dadfbd77d0e4e33874f53def5603fd6a and 12af6dc21fea1c23c3d4187afb1302a36335fc83 commits
