### ISSUE TITLE
GDPR Information while sign-ing

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#104]

**Comment by MobileMaggie** [comment]
You can use the text we developed for the ECSA newsletter form as a starting point:

https://citizen-science.us3.list-manage.com/subscribe?u=d21c3d318d533a1a044504214&id=8068ba2936

**Comment by MobileMaggie** [comment]
Another example : "Volunteering for Mozilla as a community contributor may require Mozilla and others to communicate with you at the email address that you provide in connection to your contribution and to recognize your efforts. If you contribute to Bugzilla, Mozilla Reps, or our code base, then your email address and possibly your name will be publicly available to all internet users. If you create a profile at Mozillians.org, it will be accessible to Mozilla employees and Mozilla contributors. You can edit your profile data at Profile Settings. We sometimes use contributor information from sources (such as Bugzilla) in dashboards to visually share aggregated data on the Mozilla community. An example is https://wiki.mozilla.org/Contribute/Dashboards. If possible, we try to minimize contact information that is publicly displayed."  From: https://www.mozilla.org/en-US/privacy/websites/

**Comment by frasanz** [comment]
Adding links in the sign-up  to Terms of Use, Privacy and Cookies. Closing this issues as this will be completed once https://github.com/Ibercivis/EU-CS_platform/issues/81 and https://github.com/Ibercivis/EU-CS_platform/issues/78 are closed
