### ISSUE TITLE
remove logo in front of project search and resources search

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#120]
Please remove the grey-tone circle logo that is in front of the search filters on the Projects page and the Resources page 
<img width="1213" alt="remove logo" src="https://user-images.githubusercontent.com/1629708/77253438-85733d80-6c5a-11ea-8889-f8fc56f3de8c.png">

**Comment by frasanz** [comment]
Done, it was the selector for  resources which accomplish criteria. Now there is a normal selector
