### ISSUE TITLE
put the home page search bar ON the Jumbotron

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#122]
Make the search function much more prominent by putting it right on the Jumbotron image, beneath the slogan 'WELCOME to the platform for sharing knowledge, tools, training and resources for Citizen Science.'

See this mock-up:
![slogan and search bar on jumbotron](https://user-images.githubusercontent.com/1629708/77254074-12b89100-6c5f-11ea-8287-4552b39d3185.png)

**Comment by frasanz** [comment]
I put the search bigger just below the jumbotron (see in version 0.2), if you don't like, please, reopen

**Comment by MobileMaggie** [comment]
The idea is that it should be highlighted, so that it really stands out as
the main action - if it is below the image, then it disappears into the
white background - we also state it in our deliverable as best practice!!
