### ISSUE TITLE
colour palette for text

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#126]
- Main body text on white is two shades lighter than black (second darkest grey - not the grey shown in this palette)
- Headings and emphasised text on white is the darkest blue
- Main text on a dark background (Jumbotron) is white, and secondary text is the very palest shade of pink 
- main green and pink are only used for highlight colours such as separator lines, buttons, etc NEVER text

<img width="798" alt="Palette" src="https://user-images.githubusercontent.com/1629708/77329666-92f1fb80-6d1e-11ea-9ef0-25280237956b.png">

**Comment by frasanz** [comment]
We are going to change the palette. But...Do we want to use the proposed one? (The one you put in this image). I don't  like it

**Comment by MobileMaggie** [comment]
I don't either - but if we deviate from this, then we'll have to do it for
the logo versions as well....

If you don't mind going with my suggestions for now, let's revisit the
entire colour scheme after release - we can then go back to the Agency to
ask for new logo colours as well.




ECSA <https://ecsa.citizen-science.net/> - The European Citizen Science
Association
WeObserve  <http://www.weobserve.eu/>- An ecosystem of citizen
observatories for environmental monitoring
LandSense <https://landsense.eu/> - A citizen observatory and innovation
marketplace for land use and land cover monitoring
EU-Citizen.Science- The platform for sharing, Initiating, and learning
Citizen Science in Europe

margaret.gold@mfn.berlin
linkedin.com/in/margaretgold/
Skype = margaretgold
@mobilemaggie <https://twitter.com/MobileMaggie>
+31 (0) 629353075

**Comment by MobileMaggie** [comment]
let's worry about it later - I'm closing the issue.
