### ISSUE TITLE
make the key words field larger in Projects & Resources search

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#135]
It's not clear that the box that says 'Title or keywords' is the text entry box - it needs to be much wider than the rest, and the filter drop-downs need to become much less wide
![Projects search](https://user-images.githubusercontent.com/1629708/77335498-840f4700-6d26-11ea-8aa6-b7515f0feb24.png)

**Comment by frasanz** [comment]
Not supported yet in bootstrap, but I agree on this and will try to do by hand in next release. Adding to v0.3
