### ISSUE TITLE
Create a pop-up message when a Resource profile is saved.

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#161]
Thank you 

Thank you for submitting  your resource profile. This has been sent to the EU-Citizen.Science moderation team, who will check it to ensure that all of the resources shared on the platform are indeed useful for citizen science projects and practitioners, and are of good quality. 

We will be in touch with you if we have any questions, and otherwise you will receive an alert that your resource has been moderated and published to the platform. Your resource profile will be visible to the public in the meantime, but will be marked as unmoderated. 

You can make updates or changes to this resource profile at any time, by going to the Submitted resources <link> section in your Personal Area <link> (see the top-right of the platform menu).

(also here: https://docs.google.com/document/d/1TJte783ScWth0PhEftZSed-j67rz0irf/edit#heading=h.77nb0now7pvg)

**Comment by frasanz** [comment]
Maybe with the 'message' div? I don't remember the name @vvalvesga

**Comment by frasanz** [comment]
If i left audience empty, I saw the popup

**Comment by vvalvesga** [comment]
ok, fixed it
