### ISSUE TITLE
updated Contact person text in project profile

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#170]
Please make the two remaining contact information fields (remove the telephone number) identical to the attached.
<img width="626" alt="Screenshot 2020-03-27 at 11 48 21" src="https://user-images.githubusercontent.com/1629708/77748745-2417e980-7021-11ea-9972-f48f02af7b5f.png">

**Comment by MobileMaggie** [comment]
@Fran - get in touch with me when you are working on this - I'm thinking of either dropping the contact person name field as well, and just leaving a general contact field,.

**Comment by frasanz** [comment]
Closing this as I need to work on all items pointed in  our conversation
