### ISSUE TITLE
More cleaning up the Project Profile

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#171]
- rename the 'Images and communications' section - Project Profile Images
- the image loaded first, should also be the header - we shouldn't need three images
- there should be a 'View Public Profile" view so that you can see how it looks to others.
- I submitted a logo image, but it doesn't show up anywhere

**Comment by frasanz** [comment]
rename the 'Images and communications' section - Project Profile Images
there should be a 'View Public Profile" view so that you can see how it looks to others (yes, it's planned)
I submitted a logo image, but it doesn't show up anywhere (we are waiting for logos quality before deciding what to do)

**Comment by frasanz** [comment]
rename the 'Images and communications' section - Project Profile Images
Done
    the image loaded first, should also be the header - we shouldn't need three images
Not doing becasuse we need three images
    there should be a 'View Public Profile" view so that you can see how it looks to others.
What you mean? a "preview"?
    I submitted a logo image, but it doesn't show up anywhere
Will check in next versions, depending on the logos quality
