### ISSUE TITLE
Search is only scanning title and keywords?

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#173]
Can we make search also scan the abstract? We need more than just the title and keywords, because otherwise too much will get missed out in search results, where they would have been relevant.....

Ideally, search should scan all content marked in that category!

Which brings me to another question - do we have universal search? I.e. search for "policy" and see results for Projects, Resources, Events and Blog Posts....

**Comment by frasanz** [comment]
Yes, we can do that, but I will put this for next milestone v0.4. If we have time, we can try to do in this release

**Comment by frasanz** [comment]
@MobileMaggie . We need to close this issue and open "concrete" issues:

1) Universal search
2) Search inside other fields? How are we going to order the results? Not sure if this is a priority for v0.5 as we are running out of time

**Comment by MobileMaggie** [comment]
close it - I'll raise concrete issues.
