### ISSUE TITLE
Questions and answers for the FAQ section

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#174]
In this section, we will try to answer main questions (including everything about moderation process).

e.g, we will link "Read more about our moderation process" to the proper section of the FAQ page:

http://193.146.117.217/faq/

**Comment by frasanz** [comment]
Almost complete

**Comment by MobileMaggie** [comment]
The FAQ are now updated - I have highlighted in yellow everything that is now, so that you can also make some of the edits to the FAQ page that I have made in the GDoc

https://docs.google.com/document/d/1gDNMwRFixSNnHLWVuFAZKNVF8YXcV_lpVkQGEu3L-0k/edit#
