### ISSUE TITLE
remove "British English" as a language tag and replace with "English"

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#178]
<img width="1250" alt="Screenshot 2020-03-30 at 09 48 17" src="https://user-images.githubusercontent.com/1629708/77887970-ce834d00-726b-11ea-837e-7e812fa6e7e3.png">

**Comment by frasanz** [comment]
Done, but we need to remove the British English (and American English, and Español del Colombia, etc.) from the available options when you submit a resource

**Comment by MobileMaggie** [comment]
Yes, agreed - can you please do so?

**Comment by frasanz** [comment]
I can see (for example) british english, american english, Español de Combia in the options when adding a resource. We shall remove it

![imagen](https://user-images.githubusercontent.com/456573/77924497-fee6dd80-72a3-11ea-9dcf-fc3862e727a7.png)

**Comment by vvalvesga** [comment]
it shouldn't show these options now, do you really update version?

**Comment by MobileMaggie** [comment]
it was only that one example - a bug I guess - now gone!

**Comment by frasanz** [comment]
My faul @vvalvesga , I updated localhost but checking in testing platform.
