### ISSUE TITLE
Templates for two emails (recover password and confirm email)

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#180]
Need two templates for emails:

1) We are sending an email for recovering password, we need the template

2) We are sending an email for email confirmation (while signing up), template needed

**Comment by MobileMaggie** [comment]
Here's the recovery email text
[Password Recovery Email.docx](https://github.com/Ibercivis/EU-CS_platform/files/4415290/Password.Recovery.Email.docx)

**Comment by MobileMaggie** [comment]
Here's the e-mail confirmation text
[Address Confirmation Email.docx](https://github.com/Ibercivis/EU-CS_platform/files/4415359/Address.Confirmation.Email.docx)

**Comment by MobileMaggie** [comment]
Please also build in a welcome email, with this text
[Welcome Email.docx](https://github.com/Ibercivis/EU-CS_platform/files/4415539/Welcome.Email.docx)
