### ISSUE TITLE
Latest Resource tile images all the same

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#182]
all of the 'Latest Resources' tile images are now identical! 
<img width="1167" alt="Screenshot 2020-04-01 at 09 04 27" src="https://user-images.githubusercontent.com/1629708/78108521-dc65d900-73f7-11ea-9144-b32f3ec3cb50.png">

**Comment by frasanz** [comment]
Yes, because it's the default image. Closing this as we're going to redesign the frontpage
