### ISSUE TITLE
one Project tile isn't pulling in the abstract text

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#183]
namely, Biodiversity4all
<img width="1180" alt="Screenshot 2020-04-01 at 09 03 12" src="https://user-images.githubusercontent.com/1629708/78108657-1df68400-73f8-11ea-8263-8a6d84b2878f.png">

**Comment by vvalvesga** [comment]
It seems Biodiversityall's description is '-' and in project detail you can see the aim and again the '-' description. It's a content problem.

**Comment by MobileMaggie** [comment]
aha - we need to address the content then. I can do that.

**Comment by frasanz** [comment]
In fact, promoting you to administrator

**Comment by frasanz** [comment]
Closing this, as you are now administrator
