### ISSUE TITLE
remove rating stars from Blog posts

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#187]
<img width="1012" alt="Screenshot 2020-04-01 at 22 06 10" src="https://user-images.githubusercontent.com/1629708/78181743-2638d880-7465-11ea-8923-9a955503b9c9.png">

doesn't make sense to have rating of blog posts

**Comment by MobileMaggie** [comment]
also remove the 'Review' button under blog posts 

can we open up comments instead? ONLY if we've got good spam filters, AND you have to register first AND comments are moderated

**Comment by frasanz** [comment]
Lets remove for now
