### ISSUE TITLE
set up e-mail alert when new profile submission made

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#189]
if possible, please set up the e-mail to have an end-of-day daily summary of all new profiles submitted during that day.

I anticipate that we get a lot of new profiles over the coming weeks, but after that it will fade down.

A daily summary is perfect for managing high-volume, and also for catching single profile submissions during quiet times

**Comment by frasanz** [comment]
Yes, we can schedule a script which looks in the database and send and
email with las activity, but maybe django has a default way of doing it.

Fran

**Comment by frasanz** [comment]
For sure, this is something we can do, but not a priority for v0.5 (second release). Moving it to v0.6

**Comment by MobileMaggie** [comment]
agreed, we can implement it in v0.6

**Comment by frasanz** [comment]
When the project/resource/training is submitted, send email to administrator and project submitter

**Comment by vvalvesga** [comment]
What message should we send you @MobileMaggie ? For project, resource, training and organisation

**Comment by MobileMaggie** [comment]
all three please - thanks!

**Comment by frasanz** [comment]
Hi Margaret

We will need the text to send in the email to the submitter for each case
(we will send the same email to the submitter and to the administrator)

*For project:*
*) A message when a person has submitted a project saying thanks , and that
the project will be moderated as soon as possible
*) A message when to send when the project is approved

*For resource:*
The same

*For training:*
The same

*For institution*
The same, but have in mind that we don't have the moderation process for
institutions

Fran

**Comment by MobileMaggie** [comment]
The text for all automated emails is here https://docs.google.com/document/d/1y7LALMOcukLLbcdNCdkdwhiuVMYL4m_vHrN4kYZ5y9E/edit#
