### ISSUE TITLE
make 'Publisher' NOT mandatory in the Resources profile

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#192]
...can that text entry field be made bigger so that all of the affordance text can be read?

**Comment by frasanz** [comment]
Can do, but in this case we need to make bigger all the other fields (and
to be coherent, all the others forms). If possible, I would suggest to
resume the phrase.

Fran

**Comment by MobileMaggie** [comment]
yes, I see what you mean about consistent sizing.

PUBLISHER: The publisher of the resource (or the project name, or the lead
institution).




ECSA <https://ecsa.citizen-science.net/> - The European Citizen Science
Association
WeObserve  <http://www.weobserve.eu/>- An ecosystem of citizen
observatories for environmental monitoring
LandSense <https://landsense.eu/> - A citizen observatory and innovation
marketplace for land use and land cover monitoring
EU-Citizen.Science- The platform for sharing, Initiating, and learning
Citizen Science in Europe

margaret.gold@mfn.berlin
linkedin.com/in/margaretgold/
Skype = margaretgold
@mobilemaggie <https://twitter.com/MobileMaggie>
+31 (0) 629353075
