### ISSUE TITLE
Future release: integrate with ORCID for registration and linked profiles

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#195]

**Comment by vvalvesga** [comment]
I read this in ORCID documentation: "ORCID sign-in may not be appropriate if you require stronger authentication, or specific information such as an email address, affiliation, or role." 

On the platform the user has an email to which the confirmation email is sent to create an account
You also need email or have an internal user to have associated projects and resources.
For now, I have added the ORCID field in the registration form and in the user's profile, with a link to their ORCID profile.
But if we want to be able to register with ORCID, we have to make a few changes for it to work.

**Comment by MobileMaggie** [comment]
Good catch - let's look at it as linking your profile to ORCID, rather than using it to register. We do need e-mail addresses to communicate from the platform.

**Comment by vvalvesga** [comment]
Now you can check it this, in user profile will appear ORCID link. User can added it in register form or in profile edition.

**Comment by frasanz** [comment]
Shall we close this issue @MobileMaggie ?

**Comment by MobileMaggie** [comment]
yes, it's implemented, we can close it.
