### ISSUE TITLE
use this photo for resources tile on home page

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#202]
![Vytautas-Magnus-University](https://user-images.githubusercontent.com/1629708/78458579-bc157300-76b2-11ea-895b-5916f1ff98a9.jpg)

**Comment by frasanz** [comment]
You mean for training resources? DO you have it with more resolution?

**Comment by MobileMaggie** [comment]
I don't sorry - it's from our blog. I'll look for another one

**Comment by MobileMaggie** [comment]
how about this one https://www.ceh.ac.uk/sites/default/files/P1080842%20blog%20crop%20by%20Richard%20Sylvester%20of%20Earthwatch.jpg

**Comment by MobileMaggie** [comment]
got one from our pictures library https://drive.google.com/drive/u/0/folders/17YAss7_ZxGbGjF69h1NX-v-fHdoWaKi-

**Comment by MobileMaggie** [comment]
and here's another one you can use somewhere https://drive.google.com/drive/u/0/folders/17YAss7_ZxGbGjF69h1NX-v-fHdoWaKi-

**Comment by MobileMaggie** [comment]
This is our Picture Library, that you can choose from https://drive.google.com/drive/u/0/folders/1_htrCbdsvb9Fz88YlyfIBpRNXeZcprmv
