### ISSUE TITLE
Create the category field for resources,

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#21]
Create the category field for resources, they can be
1 Tools
2  Guidelines
3  Training resources
4  Other Materials If you select this category, you will be allow to select
4-1  Libraries
4-2  Scientific Publications
4-3  Websites
4-4  Reports
4-5  Audio
4-6  Visuals
4-7  Miscellaneous

**Comment by vvalvesga** [comment]
Done 302927c2e418dfe657b3950e88cb0512a7fac48e 1002469fd0a718efb51009d480f58db2e7e4fd86 40d0364ab6d9c5504f26ea7b054ba41b798ec789
