### ISSUE TITLE
update search "clear" text

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#216]
change the text "Clear current search query, filters, and sorts" tp "Clear current search query and filters"

**Comment by frasanz** [comment]
Why? Sort is also deleted

**Comment by MobileMaggie** [comment]
the meaning is clear and it's shorter.

to be grammatically correct you'd have to say 'Clear current search query, filters, and sortation'

so otherwise, please correct to that.
