### ISSUE TITLE
put the save bottom on the top as well as bottom of profile forms

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#233]

**Comment by vvalvesga** [comment]
I've also put the save button in top of edit pages (resources and projects). 
In new resources/projects also? I consider a lineal flow so button should go at bottom.

**Comment by vvalvesga** [comment]
With what you say me @MobileMaggie , I close this issue or I do more changes.

**Comment by MobileMaggie** [comment]
Yes, please put in both - if you miss a field by accident and go back to
fill it, then it's handy to save at the top.

**Comment by vvalvesga** [comment]
Done.
