### ISSUE TITLE
POST LAUNCH: edit blog post publication dates to identical with original

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#238]
https://eu-citizen.science/blog all of them say March 31st :) Please edit to match the original date they were posted on the WP project site.

**Comment by vvalvesga** [comment]
@frasanz Can you change these post's publication dates in database? Table "blog_post"

**Comment by frasanz** [comment]
Not a priority, moving to v0.6

**Comment by frasanz** [comment]
@MobileMaggie  idone?

**Comment by MobileMaggie** [comment]
I haven't checked - are they the same now?

**Comment by frasanz** [comment]
Yes, It's not urgent, but something we need to do.
