### ISSUE TITLE
Google Analytics? Why not something more privacy oriented?

### ISSUE THREAD

**Issue by PhilippSPOTTERON** [Ibercivis/EU-CS_platform#241]
We noticed that there is Google Analytics running on the page - it would be more ethical, especially in the field of Citizen Science, to use e.g. a self-hosted Matomo (successor of Piwik) or just work with server stats.
Using "free" services by mega-corporations always means paying with the users' personal data.

**Comment by frasanz** [comment]
Good point Philips. Assigning it to me to be done as soon as possible

**Comment by frasanz** [comment]
Try to find a solution for this. Are we going to move out of google analytics? Advantages and disadvantages?

**Comment by MobileMaggie** [comment]
We don't have the scope to deal with this in this release - I think I want
to ask others in the consortium if this is something we are concerned about
or not.... maybe a mini-task force. I don't see it as urgent, and don't
want to 'unplug' google analytics until we have something else in place. We
don't have any personal data beyond email address and employer, so the
exposure is very low.

**Comment by PhilippSPOTTERON** [comment]
Thanks for the follow-up! But just to provide a better picture: for data privacy and most importantly data ethics, it doesn't matter what the website itself stores - when you include GA it tracks the visitors, their behaviour, where they come from, what they do, and so on.. so it is not only about the email addresses the website itself stores. By using "free" services like GA, you simply pay with the data and daily lives of all website visitors and there are easy to use alternatives like Matomo (either cloud or self hosted) or server statistics, which are collected already I guess. (for cloud: its basically replacing 1 line of code in a website's template)

**Comment by MobileMaggie** [comment]
thanks for the additional detail - in the short term we don't want to lose
the insight that GA currently provides us, but we do want to look properly
into what we can replace it with. Can we contact you after this release
Philipp to find how you are implementing Matomo and other solutions in
practice?

**Comment by frasanz** [comment]
Moving it to v0.6
