### ISSUE TITLE
500 Error after saving project changes after submission

### ISSUE THREAD

**Issue by PhilippSPOTTERON** [Ibercivis/EU-CS_platform#242]
We have entered a new project - then clicked save, then we wanted to change some things in the text, done that with the tab still open and clicked save again > 500 Server Error
(Windows 10, Browser Chromium-based Vivaldi)

**Comment by frasanz** [comment]
We will try to reproduce the error

**Comment by vvalvesga** [comment]
I believe it was a JS error due to SSL protocol. I fixed it but we can test again.

**Comment by frasanz** [comment]
There were also som problems while uploading images (Timeout). I'm granting
more cores to the server.

Fran

**Comment by vvalvesga** [comment]
Close this issue because it seems it has been corrected with our changes.
