### ISSUE TITLE
resource profile form won't accept new author entry

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#243]
..and I can't save it...
<img width="1440" alt="Screenshot 2020-04-07 at 10 04 40" src="https://user-images.githubusercontent.com/1629708/78645178-5e05ad00-78b7-11ea-8082-bc06362708a1.png">

**Comment by frasanz** [comment]
You need to write comma after the autor. But I maintain this issue in order to write an explanatory text in the label

**Comment by MobileMaggie** [comment]
it wasn't working with a comma either - I still got "not found"

**Comment by frasanz** [comment]
It is working for me, I promise .
[image: imagen.png]

Can you say more about your navigator?

Fran

**Comment by MobileMaggie** [comment]
ok, I'll give it a try again next time I'm going through the projects...

**Comment by vvalvesga** [comment]
Close. If it happens again, reopen this issue.
