### ISSUE TITLE
Project Profile needs designing - let's make a plan

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#247]
not a fix for today, but an improvement that should come in the next week or two.

**Comment by MobileMaggie** [comment]
first observation - the link to go to the project needs to be way more prominent, with a button up top- "Go to the project website'

under the banner (and this needs flagging better in the profile form), on the right is the Aims information - this needs a heading

then there is the abstract information - this needs a heading

to the left, this is where the logo should go

and under the logo, a very big 'go to the project website' button in our palette green

....let's get that part in place first, and then design the rest....

**Comment by frasanz** [comment]
Closing this as @MobileMaggie provided Mockup
