### ISSUE TITLE
remove "not approved" project profiles from visible Unmoderated list

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#248]
people have been making some test profiles, which I've been marking as not approved (the eye) - please remove them from the 'Unmoderated" list results.

They don't need to be deleted however - they can remain in the Personal Area of the person who submitted them. That person may want to come back and start adding real information there.

**Comment by frasanz** [comment]
Is this working with this morning explanation?

**Comment by MobileMaggie** [comment]
I have marked some as not accepted, but I continue to see them in the "not
moderated" listing - do they just take awhile to clear?

[image: image.png]

**Comment by frasanz** [comment]
I can't see your image.

**Comment by MobileMaggie** [comment]
<img width="766" alt="Screenshot 2020-05-04 at 09 34 47" src="https://user-images.githubusercontent.com/1629708/80944781-9b902400-8dea-11ea-8435-abf6b03c6060.png">
