### ISSUE TITLE
hyper link "Characteristics of Citizen Science" in Moderation, Quality Criteria & FAQ

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#249]
this work is not being promoted yet, to allow us this week for our own launch announcements, but it can already be linked to:

https://ecsa.citizen-science.net/sites/default/files/ecsa_characteristics_of_citizen_science_-_v1_final.pdf

**Comment by MobileMaggie** [comment]
Still needs hyperlinking in the "overarching criteria" section: https://eu-citizen.science/criteria/

**Comment by MobileMaggie** [comment]
also still needs hyperlinking in the "Required Criteria - Citizen Science" section https://eu-citizen.science/moderation/

**Comment by vvalvesga** [comment]
Ok, I add hyperlink in those sections.
