### ISSUE TITLE
FUTURE RELEASE: let's look at how to use the WeObserve map

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#252]
WeObserve has built this leaflets map https://www.weobserve.eu/about/cos-landscape-map/ it still needs some fine-tuning, but I'd like us to think about how:
-  we might do something similar
- we might pull in this data (it's just an underlying spreadsheet, but the data fields are difference)

**Comment by frasanz** [comment]
We need to create a full page(s) on maps, statistics, etc. So yes, go for it. Also have a look at d3.js for other graphs

https://d3js.org/
