### ISSUE TITLE
please add this event to the Events Page

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#254]
https://ec.europa.eu/info/news/pan-european-hackathon-develop-innovative-solutions-overcome-societal-challenges-related-coronavirus-2020-apr-14_en

https://euvsvirus.org/

**Comment by MobileMaggie** [comment]
please add this Webinar as well https://scistarter.org/citizenscienceasia-webinar

**Comment by MobileMaggie** [comment]
please add this event as well

**Comment by vvalvesga** [comment]
I've added the events. We have to change the design. 
Maybe hide events that have already expired. And put the blog's editor. 

I just changed some things, I have put that the place of the event is not required (there are events online or the place is not yet known). I have changed the date, now it will appear Month, day YEAR and smaller
But it won't be seen until the next update.

Close this issue but we have to improve events page
