### ISSUE TITLE
Resource description 

### ISSUE THREAD

**Issue by morganeopoix** [Ibercivis/EU-CS_platform#258]
Hi everyone, 

I have noticed that when we want to add a new resource on the platform, we can only choose a language whereas some resources could be written or available in several languages.

**Comment by vvalvesga** [comment]
The document pointed to by the url in which language is it?
I don't know if we should create a new resource by language or in the same resource include multiple languages and several links

**Comment by MobileMaggie** [comment]
the latter solution is much better indeed - can we do that?

**Comment by frasanz** [comment]
We can do, although it has some advantages and disadvantages. Need to think on this and solve in some way or another for v0.5

**Comment by MobileMaggie** [comment]
Can we discuss this today before the call with Peter Benton?

**Comment by frasanz** [comment]
Have a look at

https://docs.google.com/spreadsheets/d/14pRSlebKmWM5EHpzrWPCn2bvVu6Z4TICQDfm9-yXhwo/edit#gid=0

**Comment by MobileMaggie** [comment]
Decision: We only indicate one language for resources. In the instruction text we say "Please indicate the (main) language that the resource is made available in".
