### ISSUE TITLE
make the ECS icon clickable on profile for moderation

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#259]
my moderation flow is that I open up the profile while going through a quality criteria checklist. It would be useful if I could click in the lower left ECS icon to approve this resource or project from within the profile, and not have to go back to the overview first.

Please also make this icon clickable for moderator approval.

**Comment by vvalvesga** [comment]
It's working now in new versions, but platorm should be updated.

@frasanz when you have time, can you update platform?
