### ISSUE TITLE
inserting info about a European project

### ISSUE THREAD

**Issue by SallyReynolds** [Ibercivis/EU-CS_platform#261]
Hi, I just added info about CS Track, our European project, however i ran into a couple of issues and am not sure whether such projects should be entered into this database, first of all, our subject area is Citizen Science itself rather than a subject like physics, so i wasn't able to add this, calos we are in multiple countries which i dont think the service supports? sorry if i missed this....
just wanted to let you know
Sally

**Comment by MobileMaggie** [comment]
Hi Sally,

For now we are unfortunately only mapping the location of the Coordinator or the lead organisation - we look forward to showing global projects better in the next release. In your case, do you have multiple pilot locations, or just a range of partner locations?

Thanks for flagging your case of studying the 'Science of Citizen Science', we either need to add that to our list, or introduce "Other" and an open field.

**Comment by SallyReynolds** [comment]
Thanks Margaret, we will not be running any pilots ourselves so we just have multiple partner locations.  Can you let me know if you will be adding our project to your database so that it is findable there?
Kind regards
Sally

**Comment by MobileMaggie** [comment]
Thanks Sally - I'm just going through a moderation back-log right now, so
hopefully I'll get to that shortly :)

thanks for your patience!

Margaret




ECSA <https://ecsa.citizen-science.net/> - The European Citizen Science
Association
WeObserve  <http://www.weobserve.eu/>- An ecosystem of citizen
observatories for environmental monitoring
LandSense <https://landsense.eu/> - A citizen observatory and innovation
marketplace for land use and land cover monitoring
EU-Citizen.Science- The platform for sharing, Initiating, and learning
Citizen Science in Europe

margaret.gold@mfn.berlin
linkedin.com/in/margaretgold/
Skype = margaretgold
@mobilemaggie <https://twitter.com/MobileMaggie>
+31 (0) 629353075

**Comment by frasanz** [comment]
@MobileMaggie , Can we close this?
