### ISSUE TITLE
map

### ISSUE THREAD

**Issue by Citscilab** [Ibercivis/EU-CS_platform#265]
The map with the location is not helpful, because if you say that the project is for the netherlands, you see a dot in the center of the Netherlands zoomed in to that specific place which gives the false impression that it is only executed there. Is it possible to highlight an entire country or even all the countries where you can join?

**Comment by MobileMaggie** [comment]
Update the text on the New Project form, above the map
"Geography
Indicate the location where the project takes place when one location can be indicated, and otherwise indicate the address of the Coordinator or Leading Partner. (Enter address or click on the map)
