### ISSUE TITLE
2 search buttons

### ISSUE THREAD

**Issue by Citscilab** [Ibercivis/EU-CS_platform#266]
The 2 buttons to search at the homepage (resources or projects) are confusing. I have  pushed the ‘resources’ button several times when looking for projects, just because it’s next to the search field. Also if you want to search and just push enter you get to the resources and and you might miss the project you are looking for. 
I would recommend to make just one ‘search’ button and provide filter options (checkboxes for example like you see in booking sites) to filter for resources or projects (and maybe even more options).

**Comment by MobileMaggie** [comment]
This is a frequently recurring frustration, please add "SEARCH" to the buttons:

SEARCH
Projects

SEARCH 
Resources

**Comment by vvalvesga** [comment]
Ok, I add "search" text to these buttons

**Comment by Citscilab** [comment]
Hi thanks for the replies. However, for me it's not the word 'SEARCH', but the fact that there are TWO buttons. This is in my view very confusing. Normally search fields have one button and you can refine your search with checkboxes or dropdown menus. And as I said by default if you click enter button 1 is used, so if you look for a research and you just give an enter, you will never find it.
I suggest to add a dropdown menu where you can choose between project and resource. 
If you start on the project page, the dropdown 'project' is selected by default
If you start on the resource page, the dropdown 'resource' is selected by default
