### ISSUE TITLE
text editing

### ISSUE THREAD

**Issue by Citscilab** [Ibercivis/EU-CS_platform#267]
It would be great to have some text editing tools for projects and resources. Currently you can’t even add a break, so it’s very hard to read.

**Comment by MobileMaggie** [comment]
Integrate a WYSIWYG editor into the larger text sections of the profiles (Abstract, Aim, Description, etc...)

**Comment by frasanz** [comment]
We had this in the previous-to-first release, but we faced some format issues. But agreed with this issue. Moving it to v0.6

**Comment by frasanz** [comment]
What about using ck_editor victor?

**Comment by vvalvesga** [comment]
I've put a ckeditor insteaf of basic text field.
