### ISSUE TITLE
Error 500 saving a project

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#268]
I'm getting a 500 Error when I try to save this project, after editing the images to add a profile header https://eu-citizen.science/editProject/99

**Comment by vvalvesga** [comment]
I think it's a problem with an old image. With the new version I think this won't be a problem because project's owner will can delete or update image.

**Comment by MobileMaggie** [comment]
I was trying to update it indeed - is it on the development list to delete
it first before updating?

**Comment by vvalvesga** [comment]
Actually updating is already deleting the previous one.
There is still no delete button in version now. In the next update of the platform you can
