### ISSUE TITLE
Writing a blog post

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#270]
Hello!

While writing the blog posts for the characterization of Citizen Science, I noticed some points that could be improved in the blog posts backlog:

- Possibility to change the formatting? For now, it doesn't really work, the text doesn't appear Bold or the headings are the same as the normal text. (Maybe a possibility to access the HTML or textile?)

- The possibility to delete the picture of the article, without having to put a new one?

- This is not crucial, but in the "history" section, all the changes have been made by Margaret (although I'm pretty sure that I made them :) )

**Comment by MobileMaggie** [comment]
Add WYSIWYG editing tools for blog posts.

**Comment by luciestei** [comment]
Hi ! just a quick addition to my previous comments, would it be possible to add a function to choose/change the publication date for the blogposts? I might be super-handy to order them.
