### ISSUE TITLE
Who submitted and when?

### ISSUE THREAD

**Issue by Citscilab** [Ibercivis/EU-CS_platform#272]
On every resource and project page, I would like to see who submitted it and when!
Maybe even be able to see all editors on a project and also be able to click on such an editor to see which other projects he or she edits.

**Comment by MobileMaggie** [comment]
Put this issue on hold - it will become possible when the registered user profiles go live, and when the Community Forums are on the platform.

**Comment by frasanz** [comment]
Yes, I think this is easy to do, although a great amount of project / resources has been submitted by admin / EU-CITIZEN.SCIENCE Consortium. Moving it to v0.6 (December 2020) as @MobileMaggie suggest

**Comment by MobileMaggie** [comment]
Can it be implemented in v0.5 for all new profiles created? I.e. that the registered personal profile link is seen for all profiles that they submit?
I still need to 'add' as editor all of the individuals in the consortium who created a profile via our spreadsheet upload. I will make time for this if we can also show their personal profile link on those profiles with this release.

**Comment by claudiafabo** [comment]
All the individuals in the consortium who created project profiles via the spreadsheet upload are now added as editors of all (accepted) projects.

**Comment by jbarbaborderias** [comment]
Solved
