### ISSUE TITLE
Weird code line at the bottom of the page

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#278]
Hi! I've just noticed a weird code line at the end of each page (see screenshot)
<<<<<<< HEAD ======= >>>>>>> 38f73c1894719cc5b876b6cfce354b2af50692d4

![EUCS code line](https://user-images.githubusercontent.com/64792963/81269552-c0360700-9049-11ea-863e-0396de5f9eab.png)

**Comment by vvalvesga** [comment]
Yes, thank you. I fixed some time ago. You'll can check it in the next version.
