### ISSUE TITLE
Stats dashboard for submitted content

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#282]
collect timestamps alongside the submitted projects and resources, such that a stats dashboard can be created to show the rate of submission for each.

this stats report should be shared in the Admin dashboard

**Comment by frasanz** [comment]
Only admin @MobileMaggie ? I'm working on statistics and maybe this can be interesting to anybody

**Comment by MobileMaggie** [comment]
sure, can be for anybody - but I think I'd want the dashboard for it in Admin, and not on the public website. Let's discuss

**Comment by frasanz** [comment]
Working on it
