### ISSUE TITLE
Remove "Alpha" from top menu

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#286]
it's distorting the menu alignment

![image](https://user-images.githubusercontent.com/1629708/82030383-af644180-9698-11ea-897c-5785d4289887.png)

It should only be implemented if we can make it a corner banner, or something similar

![image](https://user-images.githubusercontent.com/1629708/82030486-ce62d380-9698-11ea-8274-9431ec4ea1b0.png)

**Comment by vvalvesga** [comment]
CLose this, it's fixed
