### ISSUE TITLE
Add a resource

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#290]
Two small things on the form to add a resource:

* "Read our blog post on Types of Resources": there is no like to the blog post.

* The default language is Arabic, I understand that this is by alphabetical order but I think having English as the default would make more sense? most of the resources are in English anyway

**Comment by vvalvesga** [comment]
First point @MobileMaggie 
I've put english language by default.

**Comment by MobileMaggie** [comment]
I'll be doing a re-design of the add-a-resource form and can pick up this correction. Therefore closing this issue.
