### ISSUE TITLE
Blog Post tiles lost their 'jigsaw puzzle' fitting

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#294]
When the blog posts displayed on https://eu-citizen.science/blog were moved to run horizontally instead of vertically - allowing the most recent or pinned posts to all be visible on top - we lost the jig-saw puzzle characteristic of the tiles, i.e. that each row does not have fixed top alignment, but sort themselves by distance between each box.

Can we get that back? It looked nicer than the big empty spaces that are created now.

**Comment by vvalvesga** [comment]
Done
