### ISSUE TITLE
Fix the "Contact Submitter" function to send emails

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#295]
I need to be able to use the "contact submitter" function on the platform to contact people who have submitted a profile. It is currently not working (apparently a GoDaddy changed password issue)

I need to be able to check that the email has been sent to them.

I need to RECEIVE THE REPLY.

**Comment by vvalvesga** [comment]
How is this? If it works, we close this issue.

**Comment by frasanz** [comment]
Please @MobileMaggie , confirm if this is working or not.

**Comment by MobileMaggie** [comment]
We have fixed the sending of emails, but I still don't have access to that
inbox for any replies that come in ....

**Comment by frasanz** [comment]
Fixed
