### ISSUE TITLE
django.db.utils.DataError: value too long for type character varying(100)

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#30]
When uploading a project, I have the following error

django.db.utils.DataError: value too long for type character varying(100)

**Comment by frasanz** [comment]
It seems to be the image

**Comment by vvalvesga** [comment]
Resolved d59ab5001bac4b815f92f4c91ce9b6823c4a4840

**Comment by vvalvesga** [comment]
I check that Django's ImageField inherits 100 character maximum size from FileField's name. And I fixed it in 300 characters as maximum in our Project's model.
