### ISSUE TITLE
Idea: link preview in social media posts

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#300]
Hello!

When I want to promote a blog post on social media, Facebook (or other social media management tools such as Hootsuite) don't recognise the picture of the article as one.
I have to choose between adding a picture to the facebook post (which makes me loose the "link preview" feature, people can't access the link by clicking on the picture) or not adding one, but the link will be displayed without a picture (or sometimes with the project logo), which is not great at all.

Would there be a way to make the picture "recognisable" by social media, to be displayed in the preview?

Many thanks in advance!

**Comment by frasanz** [comment]
Yes!, we need this (although it's not a priority for the second release). I'm moving it to v0.6 (after second release v0.5)
