### ISSUE TITLE
Change the 'subscribe to the Newsletter' text

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#303]
Hi !

there has been some changes in the newsletter recently and in the list of other citizen science projects that have been contributing to the newsletter, but I have not been able to find how to change the text on the page:
https://eu-citizen.science/subscribe/

Could you please change this text to:
Sign up to the EU-Citizen.Science newsletter to get the latest updates on citizen science initiatives across Europe. This is a joint newsletter with nine EU-funded citizen science projects: ACTION, CitieS-Health, Co-Act, CSI-COP, CS-TRACK, D-NOSES, MICS, REINFORCE and WeCount.

**Comment by vvalvesga** [comment]
Done
