### ISSUE TITLE
Review proposed data fields for Training Resources for discussion

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#309]
https://docs.google.com/document/d/10YzLmpEUr0ckzes131NoWn9C_eGqPatdFx6SC5ypUgM/edit#heading=h.gio1dvmhfnqb 
@frasanz @ @

**Comment by frasanz** [comment]
I will have a look today. By the way, do you have in the right the menu to assign to me this issue?

**Comment by frasanz** [comment]
Liked it
