### ISSUE TITLE
Create an Organisation Profile Form

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#311]
here is the google document with the Organisation metadata, the form for adding a new Organisation, and the mock-up of how Organisation Profiles should look
https://docs.google.com/document/d/10A92iKKx9Y7IxepV-BWjBBK6pvcsjhxrjp-s1X7Fl_Y/edit#
@frasanz

**Comment by frasanz** [comment]
I will have a look today

**Comment by frasanz** [comment]
Hello Margaret

I like it. We need to think a little bit in the behaviour. For example:

If I create an institution and I add a member. (Is this member added? The member needs to accept the invitation?). The same for projects and resources

**Comment by frasanz** [comment]
@MobileMaggie , we think it's better, for the first release that the user / project /resource or training resources are the ones who are added to an institution. 

e.g. 
1) The ibercivis Institution is created
2.a) I edit my profile and I'm able to add myself to Ibercivis
2.b) I edit a resource (project, etc.) I have uploaded and I'm able to add this resource to the ones created under Ibercivis
2.c) I add a new resource (project, etc.) and I can assign it to existing institutions 

**By the way:**

One person can belong to 0, 1 or more institution
One project / resource, etc. Can belong to 0,1 or more institution

**Last thing:** 
Can I add a project to an institution that has not been created?

**Comment by MobileMaggie** [comment]
Yes, that sounds like the right solution. And that would mean that you
can't add a project to an institution until after an institution is
created....but I'm wondering if we could send people to a form that lets
them do both at once? Or 'opens up' the add-an-institution data fields
within their add-a-project form?

Does the submitter of the institution need to approve the additions from
someone else? I think it would be an important security measure....

**Comment by frasanz** [comment]
Last question, yes, after implementing it we will need to add a security
check as you said, I will open an issue with this
