### ISSUE TITLE
Community Forum Structure

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#314]
This is the top-level structure for the community forum

https://docs.google.com/document/d/1QpVBK8AW9cLTUaz_kY25GFiNYT2lnX-Z_DkPczFxpvc/edit#

**Comment by frasanz** [comment]
I'm copying here. I like the structure, the only issue for me, don't you think it can be difficult to decide if a thread is in "The characteristics of Citizen science" or "The principles of Citizen Science"?

**Comment by MobileMaggie** [comment]
the idea is to have a discussion about those documents and their content -
but it's a good point, we should link to those documents in the sub text




ECSA <https://ecsa.citizen-science.net/> - The European Citizen Science
Association
WeObserve  <http://www.weobserve.eu/>- An ecosystem of citizen
observatories for environmental monitoring
LandSense <https://landsense.eu/> - A citizen observatory and innovation
marketplace for land use and land cover monitoring
EU-Citizen.Science- The platform for sharing, Initiating, and learning
Citizen Science in Europe

margaret.gold@mfn.berlin
linkedin.com/in/margaretgold/
Skype = margaretgold
@mobilemaggie <https://twitter.com/MobileMaggie>
+31 (0) 629353075
