### ISSUE TITLE
Correct typos in current project keyword list

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#316]
CORRECTED LIST = 

Botany   Climate change   Biodiversity   Artificial Intelligence   Monitoring   source criticism   fake news   online news   Special education   Maker   Fablab   Sea   Marine   Ocean   Odour   Pollution   Noses   Microorganism   Microbiology   Bacteria   Freshwater   Environment   Nature   Wildlife   Local   Coastal   Earthworm   Soil   Carbon   Birds   Garden   Citizen Observatories   environmental monitoring   communities of practice   urban nature   bird song   social innovation   local communities   welfare society   citizen science   platform   infrastructure   Bat   Conservation   Sound   Traditional Ecological Knowledge   Low literacy   biosensors   air quality   sample collection   land use land cover monitoring   earth observation   classification   deforestation   post disaster damage assessment   innovation   in-situ monitoring   Soil moisture   satellite validation   regenerative food growing   public health   mosquito   global diseases   acoustics   classrooms   schools   food storage   refrigeration   temperature   risk   images   phenology   autumn   nutrition   tea bag index   decomposition   notice boards   citizen humanities   communication   astronomy   asteroids   virtual observatory   air pollution   rainwater management   low cost air quality sensors   collaborative data analytics and knowledge extraction   citizen workshops   measurement scenarios   malaria   tuberculosis   photography   road ecology   animal-vehicle-collision   vertebrates   citizen observatory   open science   technology   Night   light pollution   location   education   online   natural history   biology   Influenza   Plants   Handwritten letters   Historical archives   Memory   Heritage   Historical Research   Invasive Mosquitoes   Invasive Plants   Digital Platform   Game   Coronavirus   protein-folding   Computer   Biochemistry   black hole   Zooniverse   Pollinators   Schools   id tools   Survey   Teachers   global   science   dragonflies   damselflies   Astronomy   citizen social science   co-researchers   citizens in a vulnerable situation   ethics   Environmental Justice   mental health   community care   youth   co-evaluation   insects   behaviour   Water   Snow   Avalanche   Phenology   Sentinel-2   Earth Observation   Nature conservation   National park   Roadkill   Emilia-Romagna   Hover-flies   Bees   Po River Delta   Italy   Snails   Journalism   Cooperative Survey   animal behaviour   breeding behaviour   wrecks   history   underwater   maritime   diving   plastics   single-use

**Comment by MobileMaggie** [comment]
Can this be fixed this week?

**Comment by frasanz** [comment]
yes, today

**Comment by frasanz** [comment]
Lets do also an editor for keywords for adminsitrator
