### ISSUE TITLE
Re-sort Audience typology to be alphabetical

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#319]
the drop-down list should be in this order:

Community Members & Citizens    
CS Project Leaders & Initiators    
CSOs & NGOs    
Educators  
Policy & Decision Makers    
Researchers & Academics    
ALL Audiences

**Comment by vvalvesga** [comment]
@frasanz
Server -> python manage.py loaddata resources/fixtures/audiences.json
Database -> in resources_resource_audience table you have to upload id's and delete old audiences in resources_audience

**Comment by frasanz** [comment]
Thanks, old data is going to be ok, right?

**Comment by vvalvesga** [comment]
Yes, if you do an update like this:
update resources_resource_audience SET audience_id = newAudience_id where audience_id = OLDAudience_id

we talk if there is any doubt
