### ISSUE TITLE
Make policy for expired users

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#323]
Maybe an script to delete expired users?

**Comment by MobileMaggie** [comment]
what is an expired user?

**Comment by frasanz** [comment]
Expired user is the user that has created an account but never activated
it. Therefore the link for activation is expired. So when the person wants
to login, he can't because he never confirmed the account and he can't
create a new account because the email is used in the platform.

The easiest approach is to delete expired accounts (accounts never
confirmed and older than the expired time older of the link for
confirmation)

**Comment by MobileMaggie** [comment]
ok great - can we align the deletion of the user with the expiry of the confirmation?

**Comment by frasanz** [comment]
Yes, right. That's the point

**Comment by vvalvesga** [comment]
I've created a cron job to delete expired users. We can configure when it's executed.
We have this commands: 
python manage.py runcrons
python manage.py runcrons --force
And for do this automatically:
python manage.py crontab add
