### ISSUE TITLE
All links in Community Forum to open in a new tab

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#326]
for example in this post http://test-api.eu-citizen.science:8000/forum/forum/community-news-8/topic/find-citizen-science-everywhere-even-in-your-kitchen-8/ a new tab should open, so that users don't leave the platform.

**Comment by frasanz** [comment]
Thanks Margaret, I forgotten to create this issue

Fran

**Comment by frasanz** [comment]
Moving to 0.6 as it is not critical.

**Comment by MobileMaggie** [comment]
Is it that hard to do? It should be a default setting. It's not a bug, but
it's reasonably critical - it takes people off our site.....

**Comment by frasanz** [comment]
Forum is going to be deleted
