### ISSUE TITLE
Community Forum is adding http to urls, even when already entered

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#327]
![image](https://user-images.githubusercontent.com/1629708/91183922-591d8a80-e6ec-11ea-8277-ca3e21b2fd01.png)

**Comment by vvalvesga** [comment]
It's the same as the other issue. 
Look how I put the link:
![imagen](https://user-images.githubusercontent.com/48445869/91418849-027e9080-e853-11ea-9a43-e34ecf91bff3.png)
This is the correct form

**Comment by vvalvesga** [comment]
![imagen](https://user-images.githubusercontent.com/48445869/91419125-54271b00-e853-11ea-81d2-04e770fc200c.png)

**Comment by MobileMaggie** [comment]
this isn't intuitive for the user - how can we make it more clear?

or are we stuck with how Machina does this?

**Comment by frasanz** [comment]
We are going to check if this is easy to change the default editor to
summernote

**Comment by frasanz** [comment]
Closing this issue and open a new to incorporate summernote as default editor
