### ISSUE TITLE
Community Forum - hyperlinking in post not clear

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#328]
When I wrote this post and added links in the text, it appeared to me that they were hyperlinked. However, once saved, they are not hyperlinked.

![image](https://user-images.githubusercontent.com/1629708/91184800-553e3800-e6ed-11ea-8c94-2229428e8321.png)

When I went back to edit the text, I selected one and then clicked on the link icon - this added a tag in my post editing window, and added a link to the post when published.

![image](https://user-images.githubusercontent.com/1629708/91184831-61c29080-e6ed-11ea-8321-b49a64a4eb2b.png)

This is really unclear for users - what can we do to fix it? Either remove the appearance of it being hyperlinked in the post text, or ACTUALLY hyperlink it....

**Comment by vvalvesga** [comment]
Well, when you add a hyperlink with the hyperlink icon, you have to select text that all of us will see and the link
In this image you can see how
![imagen](https://user-images.githubusercontent.com/48445869/91416081-2e981280-e84f-11ea-9d1f-a54d5b162a81.png)

And then in the view:
![imagen](https://user-images.githubusercontent.com/48445869/91416562-d8779f00-e84f-11ea-8972-8a3e59207df7.png)

**Comment by MobileMaggie** [comment]
that is the typical functionality for adding a link indeed, although
unusual to see the bracket tags - but what makes it NOT intuitive, is the
fact that the text changes appearance when you type a link - it gives you
the impression that it has automatically created a hyperlink. Can we change
that? Then people are used to looking for where they can turn it into a
link in the WYSIWYG....

**Comment by frasanz** [comment]
I guest it is not straightforward to change the default editor, but we can
have a look if changing the configuration, we can change the "default"
editor in forums into summernote editor.

If not, I think we need to concentrate in other issues before the launch
(and maybe create a sticky topic to explain how to use the forum)

**Comment by frasanz** [comment]
Closing this issue and open a new to incorporate summernote as default editor
