### ISSUE TITLE
Info about ORCID in the register form

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#333]
https://docs.google.com/document/d/1Sq5aAJQ24yrSOtgl6B3Y6z1Bn5GgcscQnt9kdTGt-SY/edit

From this document, and explanation on ORCID needed. @MobileMaggie, Can you provide it? A short description. It is to be into here

https://eu-citizen.science/signup/

**Comment by MobileMaggie** [comment]
add this text beside the field name:

ORCID (Your unique Open Researcher and Contributor ID, maintained by the https://orcid.org/ registry, to uniquely identify your publications, affiliations and scientific contributions with your name.)
