### ISSUE TITLE
External Links in Community Forums, always to have Link icon

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#339]
At this level, within the Sub-Forum, you can clearly see an external link due to the link icon - e.g. Wissenschaft im Dialog: http://test-api.eu-citizen.science:8000/forum/forum/b%C3%BCrgerwissenschaft-im-deutschland-14/

DO NOT show it at the higher level - as is happening here http://test-api.eu-citizen.science:8000/forum/forum/national-and-regional-cs-networks-13/ - because it is confusing (it is presented like a Sub-Forum, when it's not).

If that cannot be taken out completely, then give it the Link Icon again and don't call it a Sub-Forum.

**Comment by frasanz** [comment]
It is not critical. Machina has the option to "not to show in parent" , but apparently it is not working. Moving to 0.6

**Comment by jbarbaborderias** [comment]
Forum will be deleted due to low participation
