### ISSUE TITLE
Create an Imprint page

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#34]
1. use the same content as currently on the project website
2. add to that text the following line, where "Zip File" is hyperlinked.

Official EU-Citizen.Science logos for use in Press Releases - ZIP File [https://drive.google.com/open?id=1l8nGePbiLejXjUoPDetpKUtcKToPJNtO]

**Comment by frasanz** [comment]
Done, please review (some content is changed). Open this issue again if something has to be reviewed

**Comment by MobileMaggie** [comment]
looks good :)





ECSA <https://ecsa.citizen-science.net/> - The European Citizen Science
Association
WeObserve  <http://www.weobserve.eu/>- An ecosystem of citizen
observatories for environmental monitoring
LandSense <https://landsense.eu/> - A citizen observatory and innovation
marketplace for land use and land cover monitoring
EU-Citizen.Science- The platform for sharing, Initiating, and learning
Citizen Science in Europe

margaret.gold@mfn.berlin
linkedin.com/in/margaretgold/
Skype = margaretgold
@mobilemaggie <https://twitter.com/MobileMaggie>
+31 (0) 629353075

**Comment by frasanz** [comment]
We will add some more 'nice design' in statics pages. Daniel is working on it.
