### ISSUE TITLE
Use our palette on colour coding and highlights

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#346]
I really don't like our colours, but we do need to use them to match our logo . I.e. the colour coding for Project, Resource, etc.

![image](https://user-images.githubusercontent.com/1629708/92134782-3d139a80-ee0a-11ea-8899-dc3599877fb4.png)

**Comment by frasanz** [comment]
I'm trying to do my best in this, but in some parts it makes no sense for me to use logo colours (i.e. the "Project" red in the cards). Closing this

**Comment by MobileMaggie** [comment]
![image](https://user-images.githubusercontent.com/1629708/92323977-84ce3800-f03d-11ea-9738-fc0f8380c9f4.png)

![image](https://user-images.githubusercontent.com/1629708/92323983-8ef03680-f03d-11ea-9420-2e3632fa31e5.png)

**Comment by MobileMaggie** [comment]
![image](https://user-images.githubusercontent.com/1629708/92324735-b8f92700-f044-11ea-8260-72760777d74f.png)
