### ISSUE TITLE
take search bar and filter out of Blog page

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#347]
oops - it's showing up on the Blog page! 

![image](https://user-images.githubusercontent.com/1629708/92137272-3e929200-ee0d-11ea-8bd9-438c4262b8ab.png)

however, a way to search the blog posts would be nice - can we do a sidebar with latests posts, a Calendar list,  a category list and a tag cloud? (WordPress style - like this http://prideparrot.com/blog/archive/2014/4/blog_template_using_twitter_bootstrap3_part1)

**Comment by frasanz** [comment]
Open an issue in v0.6 to add search in blog
