### ISSUE TITLE
Menu bar needs to be made consistent throughout

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#348]
I'm seeing too many variations...we've lost the login and out, and the drop-down arrow is not clear enough for the Personal Area, I propose this Profile Icon https://www.iconfinder.com/editor/?id=2703062&hash=8b163696fe292679107b06b78d9addcffaa7b5ba8a919210d6bff530

All static pages:

**Logo graphic (which links to home) / Search / Blog / Events / Forum / Profile Icon / Log In/Out / +ADD**

and when on the search pages:

**Logo graphic (which links to home) / Home / Blog / Events / Forum / Profile Icon / Log In/Out / +ADD**

**Comment by frasanz** [comment]
Yes, I need to be sure that everything has the same identity

**Comment by MobileMaggie** [comment]
oh dear - I missed **ABOUT**

All static pages:

Logo graphic (which links to home) / Search / Blog / Events / Forum / **About** / Profile Icon / Log In/Out / +ADD

and when on the search pages:

Logo graphic (which links to home) / Home / Blog / Events / Forum / **About** / Profile Icon / Log In/Out / +ADD

**Comment by frasanz** [comment]
I moved about to the bottom, but it can be recovered in the top

**Comment by MobileMaggie** [comment]
yes, it should be on top.
