### ISSUE TITLE
Organisation type drop down still missing in Form

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#349]
vocabulary =

Governmental
Non-governmental
Academic
Private sector
Community-led
Consortium

**Comment by frasanz** [comment]
Closing this, it is done, but the database needs to be updated , but the vocabulary is this other:
[https://github.com/Ibercivis/EU-CS_platform/blob/master/src/organisations/fixtures/organisation_types.json](https://github.com/Ibercivis/EU-CS_platform/blob/master/src/organisations/fixtures/organisation_types.json)

**Comment by frasanz** [comment]
But, I like more your proposal, so going to your proposed vocabulary

**Comment by MobileMaggie** [comment]
Thanks! the one you found is quite strange and doesn't fit our
situation.... this one is from the JRC.




ECSA <https://ecsa.citizen-science.net/> - The European Citizen Science
Association
WeObserve  <http://www.weobserve.eu/>- An ecosystem of citizen
observatories for environmental monitoring
LandSense <https://landsense.eu/> - A citizen observatory and innovation
marketplace for land use and land cover monitoring
EU-Citizen.Science- The platform for sharing, Initiating, and learning
Citizen Science in Europe

margaret.gold@mfn.berlin
linkedin.com/in/margaretgold/
Skype = margaretgold
@mobilemaggie <https://twitter.com/MobileMaggie>
+31 (0) 629353075
