### ISSUE TITLE
Remove moderation icons from Cards

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#352]
![image](https://user-images.githubusercontent.com/1629708/92237393-94bc0f80-eeb7-11ea-8d84-494b5947c8ae.png)

Moderation won't happen at this level, so they aren't needed here - it just takes up space.

**Comment by frasanz** [comment]
You want it only inside the profile?

**Comment by MobileMaggie** [comment]
Yes please.
