### ISSUE TITLE
Add these new fields in the Project form

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#353]
- [X] 1. After Science topic:

 **The Participation Task(s)** (Multiple selection)
 _Please select the task(s) undertaken by participants_
Defined vocabulary = 
"Annotation
Audio or video recording
Classification or tagging
DIY hacking/making
Data analysis
Data entry
Download software for distributed computing
Finding entities
Geolocation
Identification
Learning
Measurement
Observation
Photography
Problem solving
Sample analysis
Site selection and/or description
Specimen/sample collection
Transcription"

_2. After project end date:
**Duration of the project** (If the end date of the project is not known, please indicate the approximate length of the project in X Months or X Years)
_X months / X years__

- [X] 3. After the project url:

**Geographic Extent of the Project** (Please indicate the spatial scale at which the project is implemented. In the fields further below you will be able to indicate which regions and which countries are included in this spatial scale.)
_Please indicate the spatial scale of the project._
Defined vocabulary = 
"Global
Macro-regional
National
Sub-national
Regional
City
Neighbourhood"

_4**Project Region** (If you selected 'Macro-regional' for the spatial scale of the project, please select the relevant region of the globe)
_Please select the region within with the project operates_
Defined vocabulary = 
"Africa - Northern Africa
Africa - Sub-Saharan Africa
Americas – South America
Americas – North America
Asia - Central Asia
Asia - Eastern Asia
Asia - South-eastern Asia
Asia - Southern Asia
Asia - Western Asia
Europe - Eastern Europe
Europe - Northern Europe
Europe - Southern Europe
Europe - Western Europe
Oceania - Australia and New Zealand
Oceania - Melanesia
Oceania - Micronesia
Oceania - Polynesia
World"_

5**Project Country or Countries** (If you selected ''National' or smaller or for the spatial scale of the project, please select the relevant country or countries of operation)
_Please select the country or countries within which the project operates_

- [X] 6**Project Locality** (Please describe the locality of the project, in terms of where the main participant activities take place)
_E.g. in your backyard, parks in London, rivers in Europe, online globally, etc_

7**Project Language(s)** (Please select the main language of the project - to aid searching by language on the platform)
_Please indicate the main language(s) that project activities take place in._

**DELETE** lines 62 -  67
    choices = forms.CharField(widget=forms.HiddenInput(),required=False, initial=())
    choicesSelected = forms.CharField(widget=forms.HiddenInput(),required=False, initial=())
   
    host = forms.CharField(max_length=100, \
    widget=forms.TextInput(attrs={'placeholder':'Enter the name of the institution hosting or coordinating the project'}),
    required=False)

I don't dare do it! I can't tell if it's related to something

8.After How to Participate: 
**Project Task**
_Please describe the participant task(s) in the project._

9. **Intended outcomes**
_Describe the outcomes intended to be achieved by the project_

10. After project equipment:
**External Links** (Please provide links to any external resources such as a mobile app, or instructional videos)
_Please enter a URL_

11. create this functionality: **+Add Another link**

12. New Section: **Project Documentation**

**Document Name** (Please share any relevant project documentation)
_Title of the document_

**Document Link**
_Please enter a URL_

**+Add Another Document**

13. Edit lines 181 onwards to remove longitude and latitude, they are no longer used for projects.

**Comment by MobileMaggie** [comment]
I did a lot of editing in this file - you'll want to double check that I've not broken anything.

**Comment by MobileMaggie** [comment]
**REMOVE:**

1. lines 64-66
host = forms.CharField(max_length=100, \
    widget=forms.TextInput(attrs={'placeholder':'Enter the name of the institution hosting or coordinating the project'}),
    required=False)

2. lines 102-104
    #Geography
    latitude = forms.DecimalField(max_digits=9,decimal_places=6)
    longitude = forms.DecimalField(max_digits=9,decimal_places=6)

3. line 106
  #Personal and Organizational Affiliates

4. lines 116 - 135
 #Funding
    funding_body =  forms.ModelMultipleChoiceField(queryset=FundingBody.objects.all(), widget=Select2MultipleWidget(),\
        help_text='Please enter the funding agencies of the project (e.g. European Commission). \
        Select them from the list or add your own ended by comma ', required=False, label="Funding body (Put a comma after each name to add a new funding body)")
    fundingBodySelected = forms.CharField(widget=forms.HiddenInput(), max_length=100, required=False)

    funding_program = forms.CharField(max_length=500, widget=forms.TextInput(),\
        help_text='Indication of the programme that funds or funded a project',required=False)
    #Origin information
    origin_database =  forms.ModelMultipleChoiceField(queryset=OriginDatabase.objects.all(), widget=Select2MultipleWidget(),\
        help_text='Do you know the name of the database where the project first appeared?, add it here ended by comma.',\
        required=False)
    originDatabaseSelected = forms.CharField(widget=forms.HiddenInput(), max_length=300, required=False)

    originUID = forms.CharField(max_length=200, widget=forms.TextInput(),\
        help_text='Do you know the Unique identificator of the project in the previous database?, add it here.',required=False, \
        label="Origin UID")

    originURL = forms.CharField(max_length=200, widget=forms.TextInput(),\
        help_text='Do you know the origin URL in the previous database?, add it here',required=False, label="Origin URL")

**Comment by frasanz** [comment]
Lot of work here, lets see what can be done before v0.5
