### ISSUE TITLE
Profile "Go to Project" button

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#356]
- show the full url in the left hand sidebar
- create a 'Go to Project' button top right on the profile
- same for Resources, Organisation, Training
- maybe also repeat that button on the bottom beside 'Review' and 'Follow" ?

![image](https://user-images.githubusercontent.com/1629708/92305748-580d1880-ef8a-11ea-94b9-d295a35bdbdd.png)

**Comment by frasanz** [comment]
Not sure about the website as usually it is a long and ugly one

**Comment by MobileMaggie** [comment]
In that case, continue to use either "Project Website" or "Resource
Website" (etc) under the logo, with the hyperlink - but please still create
a "Go to Project" / "Go to Resource" / "Go to Training" / "Go to
Organisation" for the top right of the profile, under the title.

It is a much better user experience.
