### ISSUE TITLE
Random order in project, resources, etc.

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#362]
First featured ones, but after this...What about having random order? (If not, old projects / resources are always on last pages)

**Comment by MobileMaggie** [comment]
Default = latest version, reverse chronological order.

I think that the "Sort by Ratings" will be the solution to finding older
project more easily, they will accumulate more reviews over time.




ECSA <https://ecsa.citizen-science.net/> - The European Citizen Science
Association
WeObserve  <http://www.weobserve.eu/>- An ecosystem of citizen
observatories for environmental monitoring
LandSense <https://landsense.eu/> - A citizen observatory and innovation
marketplace for land use and land cover monitoring
EU-Citizen.Science- The platform for sharing, Initiating, and learning
Citizen Science in Europe

margaret.gold@mfn.berlin
linkedin.com/in/margaretgold/
Skype = margaretgold
@mobilemaggie <https://twitter.com/MobileMaggie>
+31 (0) 629353075
