### ISSUE TITLE
Some improvements in the style

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#366]
- [ ] Emails  (Welcome, recover password)
- [ ] Improve my profile
- [ ] Improve Login
- [ ]  Improve Signup
- [x] Webp images Safari
- [ ] All images available in webp (with required resolution)
- [ ] Resource profiles, organisation in badge light
- [X]  Improve modal headers to add. Fixed in #378 
- [X] help_text in organisation form. Fixed in #379
- [ ]  All forms, to be consistent (style)
- [ ] Link styles
- [x] Improve Event page
- [ ] Blog fonts / Blog images
- [X] Images on Curated (at least)
- [ ] Remove Go To Resource button in the bottom
- [ ] Add info for cropping in a proper way...Maybe the box for cropping more visible

**Comment by MobileMaggie** [comment]
I get a UI//UX sketching newsletter, and this one is relevant :) to this thinking: https://mcusercontent.com/6c39369d9f6ae3134a4cc7b54/_compresseds/bff989f0-8e35-45e3-bbf1-4c70560977a1.jpg

**Comment by frasanz** [comment]
We will improve in the future
