### ISSUE TITLE
Card image for Organisations is too low-res

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#377]
I uploaded a hi-res image but it appears very blurry on the site

![image](https://user-images.githubusercontent.com/1629708/92362424-46de1c00-f0f0-11ea-9c27-a054968fa751.png)

**Comment by frasanz** [comment]
Assigned to Victor, this is a priority. Maybe change the upload to our "crop" image upload (I opened an issue for this: #380)
