### ISSUE TITLE
add 'Give additional users permission to edit' to Organisations profile

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#381]

**Comment by MobileMaggie** [comment]
I'm getting this request from several people - can it be implemented today?

**Comment by vvalvesga** [comment]
Like projects permission form selector?

**Comment by MobileMaggie** [comment]
this: 
![image](https://user-images.githubusercontent.com/1629708/92584913-89d8f480-f294-11ea-9039-58bc430aa30e.png)

**Comment by frasanz** [comment]
I would prefer to fix existing issues rather than adding new features.

**Comment by MobileMaggie** [comment]
agreed

**Comment by frasanz** [comment]
But moving to milestone 0.5.1 (to be done just after forms ar ok)
