### ISSUE TITLE
'Go to Resource' button should be the same as 'Go to Project'

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#387]
Actions shared across profiles should be identical,

**Comment by MobileMaggie** [comment]
if it's easier, it can be the button at the bottom for all of them, alongside Review and Follow/ Add to Library - but then can they all be highlighted so that they stand out? Ideally with a colour.

**Comment by MobileMaggie** [comment]
rename the button on the Training resources to say 'Go to Training'.

**Comment by frasanz** [comment]
yes, and the same than organisation
