### ISSUE TITLE
Wrong vocab in Resource type drop-down menu

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#390]
![image](https://user-images.githubusercontent.com/1629708/92416773-63fe0380-f15f-11ea-954a-3406c0bab5a5.png)

**Comment by MobileMaggie** [comment]
also wrong vocab list in the Resource form 
![image](https://user-images.githubusercontent.com/1629708/92417070-b4c22c00-f160-11ea-9286-e48ddeab8387.png)

**Comment by frasanz** [comment]
Yes, we need to change this. Can you please provide a link?

**Comment by frasanz** [comment]
To the new vocabulary

**Comment by MobileMaggie** [comment]
Collection
Dataset
Event
Image
Interactive Resource (Website)
Moving Image (Video)
Physical Object (Hardware)
Service
Software
Sound
Still Image
Text - Report
Text - Project Deliverable
Text - Guideline 
Text - Policy Brief
Text - Scientific Publication
Text - White Paper / Green Paper
Text - Book   
Text - Other
