### ISSUE TITLE
'dead' field in the Resources Form

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#391]
![image](https://user-images.githubusercontent.com/1629708/92417134-f5ba4080-f160-11ea-95fa-369d2123515b.png)

**Comment by frasanz** [comment]
These are not dead, I need to change the Category to the agreed one....This was the field to select when you put "other categories"
 With the new vocabulary, we don't need . Closing this as this will be solved with the new vocabulary
