### ISSUE TITLE
take 'curated lists' out of the new resource form

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#393]
...it should be an admin-only functionality on the profile view, not the form

![image](https://user-images.githubusercontent.com/1629708/92417259-9872bf00-f161-11ea-8753-424e2391943f.png)

**Comment by frasanz** [comment]
Reading the code, only staff users are able to see this:

https://eu-citizen.science/admin/authtools/user/?is_staff__exact=1&o=6.3.2

Can you confirm that it can be seen by non staff users?

**Comment by frasanz** [comment]
Closing this, but please @MobileMaggie , check it is solved

**Comment by frasanz** [comment]
Closing this...
