### ISSUE TITLE
Give search bar icons a colour - especially the Gold Star!!

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#394]
![image](https://user-images.githubusercontent.com/1629708/92417401-2f3f7b80-f162-11ea-8927-269d57ae91f1.png)

**Comment by frasanz** [comment]
They are in color only when you are selecting this. I prefer to maintain in this way. In this way it is clear in which section you are. What I'm doing is to put the star in yellow when you select it
