### ISSUE TITLE
Upload the Training Resources from Nadia's spreadsheet

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#398]
metadata https://docs.google.com/spreadsheets/d/1YgodDF7O--KATT1pXW7AFl1law2eXABoXZYvdVWK-MI/edit?usp=gmail

images https://drive.google.com/drive/folders/1EfvRFB-6ws1zgM7PzHsX1sWDDBKLNatu

**Comment by frasanz** [comment]
Victor did almost all of this. (Not added have empty mandatory fields)
