### ISSUE TITLE
Got an Error adding a project

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#407]

**Comment by frasanz** [comment]
Can you provide further information @MobileMaggie . Can you please test it @vvalvesga ?

**Comment by MobileMaggie** [comment]
I tried to add eu-cit. Sci and got the server error 400 when I saved. I'll
try again today.

**Comment by vvalvesga** [comment]
A normal test it's working. We need more information about what fields have been filled and with what information. Anyway, we will continue doing a battery of tests

**Comment by MobileMaggie** [comment]
it works now, so might have been a blip.

**Comment by frasanz** [comment]
I fixed it yesterday @MobileMaggie , there was an small bug
