### ISSUE TITLE
fix this issue with needing a comma to enter text

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#410]
This is far too frequent a usability issue - we need to implement a universal rule that tags or text can be entered by clicking the enter button, WITHOUT a requirement to close with a comma.

"Hi Margaret,

As a tech designer, I thought I best report initial bugs I encountered :p I didn't catch you showing us how as I was struggling to try and quickly make an account!

Please pass them on as appropriate
1) I added ACSA and then later thought to add something, but don't see a "submitted organisation" in the profile I can edit.

**2) On my profile, I wasn't able to add anything in the "interest" box. I tried citizen science, technology design, HCI, wildlife conservation, and all said "no results found"."**

**Comment by vvalvesga** [comment]
Now you can enter keys pressing enter in projects, resources, training and interest areas in profile
