### ISSUE TITLE
Give users the ability to update their email

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#411]
"Hi eu-citizen.science team, due to me changing jobs I would like to change my email adress in the profile. Yet, I was not able to change this. Could you please change it to info@susannehecker.de Thanks and best regards Susanne

Susanne Hecker , susanne.hecker@idiv.de"

- Please also update her email address for her.

**Comment by frasanz** [comment]
Yes!!
