### ISSUE TITLE
Propose using ECSA colour scheme to the consortium

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#412]
![image](https://user-images.githubusercontent.com/1629708/92479834-59d21880-f1e4-11ea-90e8-b28102f8d630.png)

![image](https://user-images.githubusercontent.com/1629708/92479884-6eaeac00-f1e4-11ea-9ecd-fefbd9fba955.png)

**Comment by MobileMaggie** [comment]
![image](https://user-images.githubusercontent.com/1629708/92480214-e250b900-f1e4-11ea-9a77-9b8725d13430.png)

**Comment by frasanz** [comment]
Like more than our palette. We can discuss with other partners.

If yes, we will need the translation of this to projects, resources,
training, organisations, etc.

**Comment by frasanz** [comment]
We will redesign
