### ISSUE TITLE
Hard test on project,  resources,  training and organisation submision

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#413]
We need to test deeply all these forms, as main bugs are raising. @vvalvesga , we need to  go on this first. #403 and #407 are related to this. So I'm closing this issues. Please, start with submit project.

- [ ] Human test and detect bugs (@frasanz , @MobileMaggie , @vvalvesga )

- [ ] Create automatic testing to pass in future releases @vvalvesga 

- [ ] Go over related files and simplify them once bugs are solved @frasanz , @vvalvesga

**Comment by frasanz** [comment]
Bugs related to projects (close when solved)

- [ ]  Fails when it is not there a "Main Organisation"

**Comment by vvalvesga** [comment]
It seems that there are things that worked before and now their behavior has changed, perhaps with the latest changes.
For the moment I have detected that the keywords are not created with the new form, with the edit form yes but there are duplicates

**Comment by vvalvesga** [comment]
Keywords in projects are now working well

**Comment by vvalvesga** [comment]
Keywords and authors now are getting with Ajax and they are saved correctly when you create or update a resource.

**Comment by vvalvesga** [comment]
I close it. We made some changes and test.
