### ISSUE TITLE
Error in Machina breadcrumbs

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#417]
clicking on 'Citizen Science Networks' in the breadcrumbs on this post
![image](https://user-images.githubusercontent.com/1629708/92585112-d290ad80-f294-11ea-8ddf-2424c725568d.png)

Gave me this Bad Gateway error

![image](https://user-images.githubusercontent.com/1629708/92585154-df150600-f294-11ea-9577-9e7494909f43.png)

**Comment by frasanz** [comment]
Can you try again? It seems to work and I was just updating the platform
few minutes ago. Maybe this it the reason.

**Comment by frasanz** [comment]
Closing this, but please reopen if the bug still is there
