### ISSUE TITLE
Text while you are trying to login and you have not confirmed your account

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#421]
"We see that your email address is in our database, but that you have not yet confirmed your address. If you did not receive the confirmation email, click here to send it again"

**Comment by vvalvesga** [comment]
I put "We see that your email address is in our database, but that you have not yet confirmed your address. Review your inbox and search the confirmation email to activate your account"

**Comment by MobileMaggie** [comment]
Can I edit that message a bit?

"We see that your email address is in our database, but that you have not
yet confirmed your address. Please search for the confirmation email in
your inbox (or spam) to activate your account"

What do they do if they can't find it - can they click a button to send it
again?

**Comment by vvalvesga** [comment]
I've updated the message. About your question, Margaret, I have to investigate more about how to do it.
