### ISSUE TITLE
CSS max-width on images in forum

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#422]
Small thing: I think the images on the forum need a max-width: 100%; in CSS so they are auto-fitted in the width.
Example: https://eu-citizen.science/forum/forum/introduce-yourself-24/topic/hi-from-the-spotteron-citizen-science-app-platform-32/
Browser: Vivaldi (Chromium based), Win10

From Philipp in the Forums....

**Comment by frasanz** [comment]
Yes!, I removed default css for forum, but need to go over imgs and some
other elements

**Comment by frasanz** [comment]
New css file  for base_forum.html

img{
max-width: 50%;
}

**Comment by vvalvesga** [comment]
I've solved it changing forum editor to ck_editor and using ck_editor_uploaded for upload images easily and with this tool, the user can play with image resolution and put image correctly according to page size.
