### ISSUE TITLE
please remove these unapproved profiles from public view

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#426]
i.e. no longer show them as 'Unmoderated', but only show them in the Admin panel

- https://eu-citizen.science/resource/69
- https://eu-citizen.science/resource/70
- https://eu-citizen.science/resource/77
- https://eu-citizen.science/resource/80
- https://eu-citizen.science/project/111
- https://eu-citizen.science/project/164
- https://eu-citizen.science/project/136

**Comment by vvalvesga** [comment]
Done
