### ISSUE TITLE
Find a way to not give an author to a blog post

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#427]
Hello,

I might have raised this issue already, but I was wondering whether it would be possible to find a way to not assign a blog post to a specific author? When I publish blog posts from other projects, they don't necessarily give me the credits of the text but I find it a little bit sensitive that my name is appearing as the author. Some of them have made the remark.
Maybe could we create a "blank" account, with a nonspecific name, to which I can assign the blog posts that are not written by us?

Many thanks in advance,

Lucie

**Comment by vvalvesga** [comment]
We'll use "Empty user" for publish blog post with "blank author"
