### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Citscilab** [Ibercivis/EU-CS_platform#429]
When I am on the project page https://www.eu-citizen.science/project/69
I click on the organization (Nature Today) right below "contact" (left below).
The link doesn't take me to the organization!

**Comment by vvalvesga** [comment]
It's a problem with Host field that we had in previous versions. I've delete link and i've put host in parentheses.
Anyway, we have to find a compatibility solution. @MobileMaggie @frasanz
