### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Citscilab** [Ibercivis/EU-CS_platform#430]
Location is sometimes set to a specific country whereas this country is only the country where the project was initiated. The project runs in more countries. If you now set the filter to another country than the one that is stated, you will not find it!
Could this be fixed?

For example: 
- For the GLOBE program the location is set to UsA and none: https://www.eu-citizen.science/project/70
However, this is a worldwide program operating in 123 countries. 
- Growapp https://www.eu-citizen.science/project/69 is setup in the Netherlands, but you can do it anywhere in the world! I

Thanks!
Matthijs

**Comment by frasanz** [comment]
Projects now belong to the countries of the partners
