### ISSUE TITLE
Unmoderated Projects error

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#431]
https://eu-citizen.science/projects?keywords=&orderby=-avg_rating&status=&country=&topic=&doingAtHome=&approvedCheck=Off

"Not Found
The requested resource was not found on this server."

**Comment by vvalvesga** [comment]
I think version is not updated. @frasanz ?

**Comment by frasanz** [comment]
There was a problem while removing projects it there is a comment on it, we get a 404 error
