### ISSUE TITLE
push notification of response to a post in forums

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#434]
We need a 'push' mechanism, that alerts people to a response to their post, and bring them back to the website.

Can this be set up?

**Comment by vvalvesga** [comment]
Now, topic owner will receive an email when someone respond his topic. Also subscriptors will receive an email if they didn't send the email. For now, there is a cron job checking every hour if there are new messages and send emails in positive case.

**Comment by vvalvesga** [comment]
@frasanz you have to configure the job in production. The automatic command is: python manage.py crontab add
