### ISSUE TITLE
Search filter return different results with orderby filter applied

### ISSUE THREAD

**Issue by vvalvesga** [Ibercivis/EU-CS_platform#436]
https://eu-citizen.science/projects?keywords=&orderby=-avg_rating&status=&country=&topic=Biodiversity&doingAtHome=&approvedCheck=On

https://eu-citizen.science/projects?keywords=&topic=Biodiversity&approvedCheck=On

These requests return different results

**Comment by frasanz** [comment]
It's happening the same with country (I think it will be solved once solved orderby)
