### ISSUE TITLE
Pictures in a blog post

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#439]
I'm uploading the news that the other RIAs are sharing with us for the Newsletter, and I had a problem that I encountered before already: A picture doesn't want to get uploaded.

Ex: for the MICS news "MICS project: Special issue of Sustainability “Citizen Science for Sustainable Cities: Investigating Nature-Based Solutions”" (I can't put the link because it is still a draft), the picture doesn't appear.
![AA3I1108](https://user-images.githubusercontent.com/64792963/96734180-8ddf5280-13ba-11eb-89fb-8992073e06bb.jpg)

Do you know where this problem could be coming from? I've tried with a png and a jpeg, but the picture won't appear.
If you could help me identify the problem, I would be able to find my way around it :)

**Comment by frasanz** [comment]
Hi

I just created a test post (yo can see it in the admin area) with the
provided image but resized (the problem is that the image is too big:
3.2MB, so the workaround is to resize it before uploading it, now is about
300KB)

Fran

**Comment by luciestei** [comment]
HI Fran,

Many thanks for this, I’ll be more careful on the picture size from now on!

Lucie
