### ISSUE TITLE
Look into automatically creating Forum thread when Project is profiled

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#444]
...technically how could it work? This could become a feature for 'white label' versions of the platform, the discussion forum as a service to the project....

**Comment by frasanz** [comment]
We can do that, but I think that maybe is crazy to have lots of threads
without any feedback. What do you think?

**Comment by MobileMaggie** [comment]
indeed, we would not implement it on our platform, as there would be majority empty threads - but it is a nice functionality to offer a national platform wanting to fork our code for their own website, showcasing only local projects - it is then a community forum service they can offer their local projects.
