### ISSUE TITLE
Link in forum not working well

### ISSUE THREAD

**Issue by Citscilab** [Ibercivis/EU-CS_platform#447]
When I click the link button in the forum, it copies the entire last sentence and doesn't make a link

**Comment by frasanz** [comment]
Check if there is another editor

**Comment by frasanz** [comment]
To install ck_editor
https://django-machina.readthedocs.io/en/stable/customization/recipes/using_another_markup_language.html?highlight=editor#example-using-django-ckeditor

**Comment by vvalvesga** [comment]
I've installed ck_editor for forum. It's easier than default editor and it's easy add a link
