### ISSUE TITLE
how to show new training modules on platform

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#453]
- the Moodle page is listed in the top-level menu "Moodle". (we can think about a better name)
- we create a Training profile for each of the modules, so that they can be searched in the usual way as all of our content and all training results are show in the same way - but then points to our own platform.

**Comment by vvalvesga** [comment]
Then, only a top level menu with link to moodle in eu-citizen.science?

**Comment by frasanz** [comment]
Yes, but let's think in the name

**Comment by vvalvesga** [comment]
Close, we've put a top level link to moodle
