### ISSUE TITLE
Delete all the "testing" actions done by the consortium

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#459]
HI! I was just wandering around on the platform as I was preparing the social media posts and I came across the review of the first project that appears on the page: https://eu-citizen.science/project/54

I guess this review was made during the testing session that we had at one of our consortium meetings. I just wanted to flag it up, in case you were not aware of this.
I don't know if there are others like that on the platform, but I think it would be better to remove the ones that are not really accurate :)

**Comment by claudiafabo** [comment]
Test review(s) to be deleted here: https://eu-citizen.science/resource/52
