### ISSUE TITLE
Keywords in new project

### ISSUE THREAD

**Issue by Nienkebeest** [Ibercivis/EU-CS_platform#460]
Hi,
I've made a new project on the EU cit sci platform (Stoepplanten - Sidewalk Plants) and I can't get the Keywords to work. It shows an error when I enter my keywords, any number and any keywords. Then it automatically selects all of the available keywords. It even includes all of the keywords when I don't select any keywords and save my project. 
Please help!

**Comment by MobileMaggie** [comment]
This is urgent - really bad keywords bug, see for  example: https://eu-citizen.science/resource/137 @frasanz

**Comment by MobileMaggie** [comment]
Please clear all of the keywords from this profile: https://eu-citizen.science/project/180

**Comment by frasanz** [comment]
I just deleted all keywords of 180, but this is a big bug and we need to go over it. @vvalvesga

**Comment by frasanz** [comment]
I think it's the same or is related with 461

**Comment by frasanz** [comment]
Hi

We cant recreate the bug, can you explain the steps to get this bug?

**Comment by Nienkebeest** [comment]
Hi,

While editing my project when I select keywords it says they are invalid or
gives some kind of error. Then it automatically selects all of the
available keywords. Whether I delete them all or not, they end up in my
saved project.

I hope this helps.

Warm regards,
Nienke Beets


Op ma 23 nov. 2020 10:19 schreef Francisco Sanz <notifications@github.com>:

**Comment by vvalvesga** [comment]
I close it because we have not been able to reproduce the error and it may have been fixed since it has not been reported again.
