### ISSUE TITLE
improve 'submit image' UI in forms

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#462]
...too many people are not understanding the prompts for both a thumbnail and header image - maybe put an example image in the form?

**Comment by MobileMaggie** [comment]
The mock-up for the form, from the second release, is here https://docs.google.com/document/d/1fUMXQ9y0YHcv7UXROvG0tF583u03nq76aUHZli8yxJo/edit

**Comment by MobileMaggie** [comment]
this is the form mock-up for the resource form: https://docs.google.com/document/d/1R6wk6_uNe_yNkPqRmpeRkelMhbGHsbcT_QGNGoR2-4w/edit

**Comment by frasanz** [comment]
It was improved in a previos release
