### ISSUE TITLE
Projects: "sort by" doesn't work

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#463]
Hi!
Nothing happens when we select a "sort by" option on the projects page; the projects keep their order

**Comment by frasanz** [comment]
Hi, Thanks Lucie

It works, but not with the featured (that is, the featured are always on top), and it seems that it is not working. We Added a "sort by featured" option, so featured are not the first ones in the other sort options.

(Featured are the first ones in the homepage)

@MobileMaggie , plase check this is ok with you

**Comment by MobileMaggie** [comment]
Yes, that's a good idea for a filter
