### ISSUE TITLE
More filters

### ISSUE THREAD

**Issue by Citscilab** [Ibercivis/EU-CS_platform#464]
I would really like a filter to search through more meta data. For example:

- Project has generated scientific output (publication)
- Project focused on policy change
- part of research cycle (developing - data collection - analysis) 
- level of participation (crowdsourcing-...-extreme)
- which of the 10 principles apply to the project
- funded by (government/(EU)funds/)
- Successful in (amount of data/participants/outreach)
- Suitable for schools (primary/middle/high)

These are just some things I can think of now, but for me as a user, this would be a big advantage to use the website instead of just using Google.

**Comment by frasanz** [comment]
Thanks for the ideas!!, We will see how to implement them

**Comment by frasanz** [comment]
Done some of them
