### ISSUE TITLE
take this profile out of 'training' and turn it into 'resource'

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#467]
...it's not a training - it was mis-filed

https://eu-citizen.science/training_resource/137

**Comment by frasanz** [comment]
You have the book/hat button in the bottom of the training profile to do
that

Fran

**Comment by MobileMaggie** [comment]
it doesn't work for turning OFF training...

**Comment by frasanz** [comment]
If you click hat is training. If you click book is resources. Please @Victor
Val Vesga <vval@bifi.es> check this is working

Fran

**Comment by MobileMaggie** [comment]
once clicked, the hat is no longer clickable - do I click book to turn it
into a resource?




       ECSA <https://ecsa.citizen-science.net/> - The European Citizen
Science Association
       WeObserve  <http://www.weobserve.eu/>- An ecosystem of citizen
observatories for environmental monitoring
       LandSense <https://landsense.eu/> - A citizen observatory and
innovation marketplace for land use and land cover monitoring
       EU-Citizen.Science- The platform for sharing, Initiating, and
learning Citizen Science in Europe

      margaret.gold@mfn.berlin
      linkedin.com/in/margaretgold/
      Skype = margaretgold
      @mobilemaggie <https://twitter.com/MobileMaggie>
      +31 (0) 629353075

**Comment by MobileMaggie** [comment]
that was the trick - it's a toggle - either book or hat - I was thinking I
had to un-click the hat....

**Comment by frasanz** [comment]
Yes, click the book to convert to a resource. Click the hat to convert to a
training

**Comment by victor** [comment]
I see you keep @-mentioning the wrong people
