### ISSUE TITLE
Changes in images on projects/resources

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#470]
When submitting image, in the popup

- Say that you need to make zoom until the image covers all the box
- White background instead of black background when the image doesn't cover all the box

**Comment by vvalvesga** [comment]
i've put the  message " make zoom until the image covers all the box" in the popup

**Comment by frasanz** [comment]
What about white background?

**Comment by vvalvesga** [comment]
I've just do it, I draw a white rectangle in case of image be more little than final resolution image, so borders will be white instead of black

**Comment by frasanz** [comment]
Great, thanks. I'm CCing Antonella as she is a little bit worried about
this and she will be happy to know that new images will not have black
background.

We will need to go over old images and re-upload them to have white
background, but this is something we can do after 15 december.

Fran

**Comment by frasanz** [comment]
Thank you Fran and Team for your hard work with fixing the bugs.


In so doing, you will contribute to make happy the platform's users and make pleasant and appealing their experience of the platform.


Kind regards,


Antonella




Dr. Arch. Antonella Radicchi
PhD Urban Design and Planning, Chartered Architect
Research Associate | Wissenschaftliche Mitarbeiterin

Museum für Naturkunde Berlin
Research Uniti: Science in Society
Invalidenstraße 43 — 10115 Berlin

PM EU-Citizen.Science<https://eu-citizen.science/>

Watch our teaser!: https://eu-citizen.science/about/


[X]
________________________________
From: Francisco Sanz García <frasanz@bifi.es>
Sent: Tuesday, December 1, 2020 5:05:32 PM
To: Ibercivis/EU-CS_platform
Cc: Ibercivis/EU-CS_platform; Assign; Radicchi, Antonella
Subject: [EXT] Re: [Ibercivis/EU-CS_platform] Changes in images on projects/resources (#470)

Great, thanks. I'm CCing Antonella as she is a little bit worried about this and she will be happy to know that new images will not have black background.

We will need to go over old images and re-upload them to have white background, but this is something we can do after 15 december.

Fran

On Tue, 1 Dec 2020 at 16:54, vvalvesga <notifications@github.com<mailto:notifications@github.com>> wrote:

I've just do it, I draw a white rectangle in case of image be more little than final resolution image, so borders will be white instead of black
