### ISSUE TITLE
curated list function not working

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#475]
just tried to add https://eu-citizen.science/resource/137 to our curated list / gold star selection, saved, but it does not show up.

**Comment by frasanz** [comment]
I just addet it to "Impact and evaluation" and it worked

https://eu-citizen.science/curated/

**Comment by MobileMaggie** [comment]
I was trying to save it to Initiation... Can you try that too?

**Comment by frasanz** [comment]
Yes, done
