### ISSUE TITLE
Suggestion: form to publish external news

### ISSUE THREAD

**Issue by luciestei** [Ibercivis/EU-CS_platform#476]
Hi! This is just a suggestion, but I came across this project website that allows people to submit ideas and news to be published on the website. If we want to allow other projects to use our platform as a news medium, it would be nice to consider something like that.

https://watermining.eu/news/

**Comment by frasanz** [comment]
The blog already fulfills that purpose, but it’s a good idea to enable a form for submitting potential news. We can include that in our next iteration. I’ll close this suggestion, but it’s noted for future consideration.
