### ISSUE TITLE
The Dutch translation

### ISSUE THREAD

**Issue by buijsp** [Ibercivis/EU-CS_platform#477]
Even on the homepage there are several problems with the Dutch translation.
Where can I find possibilities to correct or report

**Comment by frasanz** [comment]
Thanks for your feedback

In order to improve the translation, for us the best option is to edit the
po file for your language (locate here for dutch):
https://github.com/Ibercivis/EU-CS_platform/blob/master/src/locale/de/LC_MESSAGES/django.po

If you have a github account you can do directly in the previous link, if
not, you can download it here
https://raw.githubusercontent.com/Ibercivis/EU-CS_platform/master/src/locale/de/LC_MESSAGES/django.po
,
edit with your favourite text edit software and send back to us:
frasanz@bifi.es ot vval@bifi.es



@Victor Val Vesga <vval@bifi.es> , can you please update the po files
before editing it?

**Comment by vvalvesga** [comment]
it's updated.
These links are for german language
Links are:
https://github.com/Ibercivis/EU-CS_platform/blob/master/src/locale/nl/LC_MESSAGES/django.po

https://raw.githubusercontent.com/Ibercivis/EU-CS_platform/master/src/locale/nl/LC_MESSAGES/django.po

**Comment by vvalvesga** [comment]
In "msgid" is the english and in the "msgstr" is the place where you have to translate in dutch.

**Comment by buijsp** [comment]
Hi,

 

When I am finished with the translation what do you want me to do with the translated file?

 

Thanks,

 

Peter

 

Van: vvalvesga <notifications@github.com> 
Verzonden: woensdag 20 januari 2021 14:43
Aan: Ibercivis/EU-CS_platform <EU-CS_platform@noreply.github.com>
CC: buijsp <pbu@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Ibercivis/EU-CS_platform] The Dutch translation (#477)

 

it's updated.
These links are for german language
Links are:
https://github.com/Ibercivis/EU-CS_platform/blob/master/src/locale/nl/LC_MESSAGES/django.po

https://raw.githubusercontent.com/Ibercivis/EU-CS_platform/master/src/locale/nl/LC_MESSAGES/django.po

**Comment by vvalvesga** [comment]
Hi 
If you have a github account you can edit this file https://github.com/Ibercivis/EU-CS_platform/blob/master/src/locale/nl/LC_MESSAGES/django.po and save it. Then you "commit & push"(upload) that change.
And if you don't know how or you haven't got a github account you can send me an email to vval@bifi.es and I will upload it

**Comment by buijsp** [comment]
This is what i get when I try to upload the changes…

 

Peter

 

Van: vvalvesga <notifications@github.com> 
Verzonden: woensdag 20 januari 2021 17:21
Aan: Ibercivis/EU-CS_platform <EU-CS_platform@noreply.github.com>
CC: buijsp <pbu@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Ibercivis/EU-CS_platform] The Dutch translation (#477)

 

Hi
If you have a github account you can edit this file https://github.com/Ibercivis/EU-CS_platform/blob/master/src/locale/nl/LC_MESSAGES/django.po and save it. Then you "commit & push"(upload) that change.
And if you don't know how or you haven't got a github account you can send me an email to vval@bifi.es <mailto:vval@bifi.es>  and I will upload it

**Comment by vvalvesga** [comment]
I don't see any text or image.

**Comment by buijsp** [comment]
Sorry it seems the screenpicture disappeared.

I was working in Github Desktop and I tried to commit the changes but a message was displayed that I have no write access to change the file.

 

 

 

Van: vvalvesga <notifications@github.com> 
Verzonden: woensdag 20 januari 2021 19:36
Aan: Ibercivis/EU-CS_platform <EU-CS_platform@noreply.github.com>
CC: buijsp <pbu@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Ibercivis/EU-CS_platform] The Dutch translation (#477)

 

I don't see any text or image.

**Comment by vvalvesga** [comment]
send me the po file and I will update it

**Comment by victor** [comment]
@frasanz can you please double check your mentions before posting? thanks

**Comment by frasanz** [comment]
Yes @victor , sorry. I answered to this thread using the email and gmail autocompleted it.

**Comment by buijsp** [comment]
Van: vvalvesga <notifications@github.com> 
Verzonden: woensdag 20 januari 2021 21:13
Aan: Ibercivis/EU-CS_platform <EU-CS_platform@noreply.github.com>
CC: buijsp <pbu@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Ibercivis/EU-CS_platform] The Dutch translation (#477)

 

send me the po file and I will update it

**Comment by vvalvesga** [comment]
Nothing adjunt

**Comment by vvalvesga** [comment]
Update it. c503bbae00e272034eb04de17f5b68cef988e6f1 
Close
