### ISSUE TITLE
Reduce size of the header in homepage

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#478]
Reduce the size of the header

![image](https://user-images.githubusercontent.com/456573/107194520-702d0c00-69f0-11eb-9ab8-a1d393e6c4a7.png)

To match other headers size (e.g. Blog)

**Comment by vvalvesga** [comment]
Done. I've also changed forum header

**Comment by frasanz** [comment]
Now, there is a white space between header and the "tools" , "projects", etc line, reopen

![image](https://user-images.githubusercontent.com/456573/107244750-aa1d0300-6a2e-11eb-82c0-15575c5d7dc0.png)

**Comment by vvalvesga** [comment]
Done
