### ISSUE TITLE
Move the social media line just below header , and add instructions to help in translation

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#479]
1) move
![image](https://user-images.githubusercontent.com/456573/107194963-ffd2ba80-69f0-11eb-90b6-75e7cb59387c.png)

just below the header, 

2) and add the phrase:  Do you want to help with translation? please click here

3) and provide complete instructions on how to translate to Claudia so she can make  proofreading, 

4) and create a page with the instructions

**Comment by vvalvesga** [comment]
the texts need to be changed according to the drive document, @frasanz
