### ISSUE TITLE
Add "owntraining" field

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#480]
In resources, add "owntraining" field so, the administrator can tick the training "when editing" and mark a training as "owntraining". We will use it to customize the look of "own resources"

**Comment by vvalvesga** [comment]
I did these in https://github.com/Ibercivis/EU-CS_platform/commit/f12e628b6e0fc9f18b158cecaa5a871f22d74fe5
But now only from administrator panel we can mark a resource as own

**Comment by frasanz** [comment]
Ok, hay que hacer el migrate en http://51.75.255.90:8000/, para ver como el
administrador lo puede cambiar

**Comment by vvalvesga** [comment]
I've update it. In administrator panel. Maybe you want button in frontend.

**Comment by frasanz** [comment]
Yes, better in the frontent

**Comment by vvalvesga** [comment]
Done
