### ISSUE TITLE
Add timezone to events 

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#486]
Add the timezone to the event

**Comment by vvalvesga** [comment]
How? 
Now, it's in UTC by default, hours are saving in UTC in database. If you want we can show "HH:MM UTC" text. Only one format. 
Other possibility is maybe with a timezone selector

**Comment by frasanz** [comment]
Yes, I think it's a good idea to have a timezone selector

**Comment by frasanz** [comment]
Already done in the last version
