### ISSUE TITLE
Add sentence to "Our Gold Star Selection"

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#487]
The EU-Citizen.Science consortium has curated a selection of Gold Star citizen science resources to help you get started with designing and launching your own citizen science project **or simply learn about citizen science**, categorised across the project lifecycle.

We received the suggestion to add the text in bold to the sentence at the top of this page: https://eu-citizen.science/curated/
This sentence is part of the translated static part. We can add in it English, but what is the next step to change all translations?

**Comment by vvalvesga** [comment]
> 
> 
> The EU-Citizen.Science consortium has curated a selection of Gold Star citizen science resources to help you get started with designing and launching your own citizen science project **or simply learn about citizen science**, categorised across the project lifecycle.
> 
> We received the suggestion to add the text in bold to the sentence at the top of this page: https://eu-citizen.science/curated/
> This sentence is part of the translated static part. We can add in it English, but what is the next step to change all translations?

They have to translate that phrase again

**Comment by claudiafabo** [comment]
Has the sentence been added to the test version (in English at least)?

**Comment by vvalvesga** [comment]
Yes, I've just updated it.

**Comment by claudiafabo** [comment]
The phrase is showing now but half of it is in English for all languages. See how it shows in French, for example. I have marked in bold the part in English that shows in every language.
Le consortium EU-Citizen.Science a sélectionné des ressources en sciences participatives Gold Star de science participative **to help you get started with designing and launching your own citizen science project or simply learn about citizen science, categorised across the project lifecycle.**
