### ISSUE TITLE
Improve captcha in "contact" as we are receiving spam 

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#493]

**Comment by vvalvesga** [comment]
I've updated recaptcha to v3. It's more secure. it is based on a scoring system. I hope this solves the spam problem

**Comment by frasanz** [comment]
![image](https://user-images.githubusercontent.com/456573/109135337-3c274a00-7757-11eb-8229-90774d6ffeb6.png)

**Comment by vvalvesga** [comment]
we left it as it was, recaptcha v2 and in high security. Close and if there are still problems we look for another captcha
