### ISSUE TITLE
Search bar showing not accessible content

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#495]
If you write "making" in the search bar it will show via drop down three options/things you might be searching for. One of them is "Documentary: Citizen Science Revolution - Making Sense". If you click on it, nothing shows (it's not a project, nor resource, etc.).
The same happens when you put in "wild". Nothing shows up when clicking on "Wild Days" or on "Wild Honey Bee Study" or on "Farmer’s Wildlife Calendar: Climate Tracker". Is this showing projects/resources that were not accepted when being moderated?

**Comment by vvalvesga** [comment]
Yes, this is happening because there are some resources in hidden status, we have to change filter so they don't go out
And other problem it's change in search filter , sometimes clicking not going to the resource page
