### ISSUE TITLE
Host and Lead Organisation showing double on the project profile

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#496]
See: https://eu-citizen.science/project/21 and https://eu-citizen.science/organisation/73
On the project profile, at the bottom left in Contact it showed "MUSEUM FUR NATURKUN... (Host)". This was not clickable, so I added MfN as the main organisation. Now, MfN shows twice on the project profile and the project shows twice on the organisation profile. This is because MfN is written in both fields: Host and Main Organisation. Do we need Host? It seems to me that this is not a field that people/users can fill in when then submit a project anyway...

**Comment by jbarbaborderias** [comment]
Solved
