### ISSUE TITLE
Access to resource through "direct" URL not working

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#497]
While one can access resources through the platform (going to https://eu-citizen.science/resources and clicking on a resource), direct access to resources through the URL of a resource isn't working. I get Server Error (500).
Random examples of not working resources:
https://eu-citizen.science/resource/19
https://eu-citizen.science/resource/142
https://eu-citizen.science/resource/148
https://eu-citizen.science/resource/135
If I access a resource, bookmark it as favourite and then want to access it through the saved URL, it won't open.

**Comment by claudiafabo** [comment]
...all links above are working when I click on them. But not if I copy-paste them into a new tab in my browser.

**Comment by frasanz** [comment]
Traceback (most recent call last):
  File
"/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/exception.py",
line 34, in inner
    response = get_response(request)
  File
"/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py",
line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File
"/home/ubuntu/.local/lib/python3.6/site-packages/django/core/handlers/base.py",
line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./resources/views.py", line 148, in resource
    previous_page = request.META['HTTP_REFERER']
KeyError: 'HTTP_REFERER'

**Comment by frasanz** [comment]
Removing "critical" tag to solve previous issues before this one

**Comment by claudiafabo** [comment]
Alright. The same happens with projects. There is no problem with organisation profiles
