### ISSUE TITLE
User workflow in ECSA individual membership

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#505]
- [x] The user profile has an ECSA tab where ECSA related information is shown
- [x] The user has the option to apply for individual ECSA membership while registering. The system sends an email with information about how to proceed with payment. This information is also in the profile panel, in the ECSA tab.
- [x] The user has the option to apply for individual ECSA membership at any moment through the profile panel in the ECSA tab. When applied the system sends an email with information about how to proceed with payment. This information is also in the profile ECSA tab.
- [x] The user has the option to remove ECSA membership at any moment (in the ECSA tab). A modal with "Are you sure?" is shown.
- [x] When applied for membership, the user will have the option "claim for payment revision" in the ECSA panel
- [ ] When approved membership, the user will receive a welcome email. Information about all the things that can be done being an ECSA member is show in the ECSA tab.
- [ ] When approved membership, there is an icon in the user profile showing that he/she is a member
- [ ] Explore automatic invoice (@claudiafabo , waiting your response from Nadia)

**Comment by vvalvesga** [comment]
I'll need the subjetct and the message for the second point. For now, I put an example message

**Comment by frasanz** [comment]
Another app is going to manage ECSA membership
