### ISSUE TITLE
User texts/emails in ECSA membership for users

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#506]
We need the following texts

**In the ECSA profile panel:**

- [ ] If you are not a member, say the benefits of being a member and something about the two options of being a member
- [ ] If you have applied for membership as individual, show how to do the payment and further instructions
- [ ] If you are an ECSA member, show the things that can be done as ECSA member

**email**

- [ ] When applied for membership, further instructions on how to proceed with the payments
- [ ] If membership is approved, a welcome email

**Comment by jbarbaborderias** [comment]
This involves another app (anyway i think it is almost solved)
