### ISSUE TITLE
Organisation Workflow in ECSA membership

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#507]
**Important**: This workflow is made by the person who owns the organisation.

- [x] The organisation profile has an ECSA tab where the following related information is shown
- [ ] The organisation can apply for ECSA membership in the organisation panel.  There is information of the advantages for an organisation to be an ECSA member. If applied hhe system sends an email with information about how to proceed with payment and this new information is shown also in the organisation profile panel
- [x] The organisation can cancel ECSA membership. A modal with "Are you sure?" is shown
- [x] When applied for membership, the organisation will have the option "claim for payment revision" in the ECSA panel
- [x] When approved membership, the organisation will receive a welcome email. Information about all the things that can be done being an ECSA member is show in the ECSA tab.
- [ ] When approved membership, there is an icon in the user profile showing that he/she is a member
- [ ] Explore automatic invoice (@claudiafabo , waiting your response from Nadia)
- [ ] The organisation can name up to three delegates (to become ECSA members)

**Comment by jbarbaborderias** [comment]
Noted and almost solved (this is related to another app)
