### ISSUE TITLE
text/emails in ECSA membership (for organisations)

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#509]
We need the following texts

**in the organisation-ECSA profile panel**
- [ ] if your organisation is not a member, say the benefits of being a member and something about the two options of being a member
- [ ] If applied for organisation membership, show how to do the payment and further instructions
- [ ] If the organisation is ECSA member, show things that can be done as ECSA member

**email**
- [ ] When applied for membership, further instructions on how to proceed with the payments
- [ ]  If membership is approved, a welcome email

**Comment by jbarbaborderias** [comment]
Noted, (issue of other app)
