### ISSUE TITLE
JUNE2020: Research phases - level of involvement

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#528]
I would be helped with a tick-box at the projects to indicate in which phase citizens are involved, e.g. setting research question, collecting data, analyzing data, dissemination, policy impact, etc. It makes it easier to look for inspiration/examples.
Add. Claudia: If we add this, we should also be able to filter projects through this.

**Comment by frasanz** [comment]
Two consecuentes:

- [ ] advanced search: add by participation tasks
- [ ] Show participation tasks in project profile

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all JUNE2020 in #616
