### ISSUE TITLE
JUNE2020: Research group profiles

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#529]
Many people would prefer to have visibility from their research group rather than their institution (particularly when they belong to very large ones...).
Also NGOs, companies, and other actors in citizen science - that might help match making for projects and make the platform community active.
In addition, those being students and working on CS related subjects would most probably like to be able to identify their peers and therefore have the opportunity to appear in the research group profile.

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all JUNE2020 in #616
