### ISSUE TITLE
WEBSITE - General: When it gets translated, the layout changes and needs improvement

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#534]
In the head menu e.g. the “Hinzufügen”/”Add” button is cut off if one is not logged in. It is also not that beautiful to have the “Open Call” button in two rows in German. This also happens in other languages, e.g. French.

![image](https://user-images.githubusercontent.com/82102786/114033200-550a3b80-987d-11eb-8101-fd3d06f22bab.png)

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - General in #615
