### ISSUE TITLE
WEBSITE - General: Some parts are not translated, they appear in English.

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#535]
This is related to the German version, but it happens in other languages too.
1. Parts of the filter options are still shown in English (Status, Topics, Doable at home) on following sites: 
▪	https://eu-citizen.science/projects
▪	https://eu-citizen.science/resources 
▪	https://eu-citizen.science/training_resources 
▪	https://eu-citizen.science/organisations 

2. In the section “About”, the paragraph about CS principles is completely shown in English. https://eu-citizen.science/about/ 

3. On the first page, the line “The static part of the platform has recently …” right below the search field is in English too. 
![image](https://user-images.githubusercontent.com/82102786/114034747-c1396f00-987e-11eb-8a1d-72acffdcea2e.png)

4. In “Events” of the top bar, the titles “Past events” and “On going Events” are not translated into German. https://eu-citizen.science/events 

5. All topics in the bottom bar are not translated (Nutzungsbedingungen, Datenschutz, Impressum, …)

6. When adding content with “Add”, many parts are available in English only. Also, the German translation needs some revision. (e.g. sometimes the punctuation is just not right or missing completely).

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - General in #615
