### ISSUE TITLE
blog.models.DoesNotExist

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#54]
blog.models.DoesNotExist in home page (I did python manage.py migrate)

![imagen](https://user-images.githubusercontent.com/456573/75334354-f86ddc00-5887-11ea-9694-97c8e806800b.png)

**Comment by vvalvesga** [comment]
Resolved it. aae65fad0625cd49e3bbbcd0fcbb8c6666a53670
