### ISSUE TITLE
Website - First Page: Boxes are confusing

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#540]
1. The boxes are too big. 
2. The pictures in relation to the text within the boxes are too big.
3. Limit the keywords to 3-5 per project.
4. Reviews are not necessary in every box. In the beginning, when no stars are visible (because no reviews exist so far), it does not help the projects. For example, it looks like the right project is far better than the left one (even though there are no reviews given so far).
![image](https://user-images.githubusercontent.com/82102786/114044103-30b35c80-9887-11eb-806e-2cfe212cd95c.png)

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - First Page in #614
