### ISSUE TITLE
WEBSITE - First page: Titles should stand out more

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#546]
The titles of the topics above the boxes should stand out more. I nearly overlooked them between the boxes. I would make the lines between the categories thicker. Or the boxes on the first page could be smaller? 
![imagen4](https://user-images.githubusercontent.com/82102786/114407318-8f8b1580-9ba8-11eb-8d8a-3c66cae77c4b.PNG)

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - First Page in #614
