### ISSUE TITLE
WEBSITE - Projects: Keyword boxes

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#548]
![imagen 5](https://user-images.githubusercontent.com/82102786/114408901-2c9a7e00-9baa-11eb-9d2b-c9b046007823.PNG)

Keyword boxes should be the same colour as the website itself (or darker) to better distinguish them (but not as dark as the colour they have when hovering over them)

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - Projects in #613
