### ISSUE TITLE
WEBSITE - Projects: Differentiate Specific CS Projects and National Platforms 

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#549]
"What is the definition for _project_ in this menu topic? I thought that specific CS projects would be shown here. Why are projects like _EU.Citizen-Science_ visible in the results or even national platforms for CS? I would differentiate here and / or describe the content more clearly."

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - Projects in #613
