### ISSUE TITLE
WEBSITE - Projects: End date and status are not accurate

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#551]
When selecting a project, one can see the status, starting point and the end date.

In some projects this is not accurate. The end date is already reached but the status is still “active”. Maybe this could be automated? E.g. when reaching the end date, the status could automatically be changed to “completed"

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - Projects in #613
