### ISSUE TITLE
WEBSITE - Resources: Unclear filter, too much resource types to choose

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#554]
The filter for the resources is unclear, because there are a lot of resource types to choose from. I would prefer a dropdown menu with carefully chosen categories when hovering over the topic “resources” in the menu bar. Alternatively, the filter could be reduced to a few clear categories to choose from.

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - Resources in #612
