### ISSUE TITLE
WEBSITE - Resources: Show the options only when the content it's available

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#556]
![Imagen6](https://user-images.githubusercontent.com/82102786/114559173-bc543100-9c6b-11eb-8f6c-df185b64c62b.png)
I would only show those languages in the filter menu, for which content is available. So if for Estonian no texts are available, I would not show the option if this is possible to code. Actually this exclusion system is useful in all filter options. So if there are no “collections” in resource types for the topic “Introduction to CS”, don’t show the option. It’s easier to search for specific content like that.

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - Resources in #612
