### ISSUE TITLE
WEBSITE - Resources: Assign the resource to only one of the main topics

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#558]
It should only be possible to assign one resource to one of the main topics “Projects”, “Training”, “Events”, “Organisations”. Otherwise the content is redundant and the system is confusing. The website of an organisation for instance should not be mentioned in “Resources” as a website and in “Organisations

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - Resources in #612
