### ISSUE TITLE
WEBSITE - Blog: Explanation about how the blog site works

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#568]
Maybe I cannot write a Blog post because I have not added a project and only project leaders can do that? Anyways, I cannot find the function to answer/ comment or to write a blog post. An explanation on the blog site would be good to know who can contribute to it and how.

**Comment by claudiafabo** [comment]
Closing as we are grouping all blog improvements here [#623](https://github.com/Ibercivis/EU-CS_platform/issues/623)
