### ISSUE TITLE
WEBSITE - Forum: Signs from formatting are visible

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#573]
https://eu-citizen.science/forum/forum/the-eu-citizenscience-project-2/topic/welcome-from-the-ecsa-team-34/?post=56#56

![Imagen8](https://user-images.githubusercontent.com/82102786/114568942-dd6d4f80-9c74-11eb-8616-989db59088a6.png)

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - Forum in #610
