### ISSUE TITLE
WEBSITE - Moocs: More information about new training modules

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#575]
In the blog, there is a post about the new training modules, however no information is given about them before being directed to the training platform. It would be useful to see some of the information given in the blog post when clicking on the MOOCS button before being redirected to the https://moodle.eu-citizen.science/ site.

**Comment by Javier-Gasca** [comment]
Closing as we are grouping all WEBSITE - Moocs in #609
