### ISSUE TITLE
WEBSITE - Representation of countries: Few countries are represented

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#589]
On the front page, the first thing to see is diverse projects from various countries. I do not know how these projects are sorted or chosen to be shown, but only a few countries are represented here (UK, Sweden, Spain). It would be great if the projects here would not always be the same but would be randomly mixed every time the site is refreshed. Like that, also the other countries are regularly represented. But maybe this is already the case already?

**Comment by jbarbaborderias** [comment]
Noted, for the moment the projects shown on the homepage are the most recent ones uploaded.
