### ISSUE TITLE
WEBSITE - Representation of countries: Only add those projects that are from or usable in the EU.

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#590]
I do not understand why projects from and for Ghana only (https://eu-citizen.science/project/117) are shown on this website (not the only project from outside the EU). It is surely a good project, but on an EU platform, I expect to find projects from or at least usable in the EU. For this, a worldwide CS platform would be better suited in my opinion.

**Comment by jbarbaborderias** [comment]
Noted, we pass the note to the moderators
