### ISSUE TITLE
Android version - Forum: Top menu bar doesn't show all the options

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#593]
![imagen11](https://user-images.githubusercontent.com/82102786/114708171-5333f280-9d2b-11eb-979c-a60a9a7ff645.PNG)
The top menu bar is cut off on the right side from “Registrierung”/“Sign in”

**Comment by frasanz** [comment]
Closing as we are grouping all phone lookandfeel issues in #604
