### ISSUE TITLE
Android version - Blog: Pictures do not adjust to the right size within the blogs

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#596]
![imagen14](https://user-images.githubusercontent.com/82102786/114708761-1288a900-9d2c-11eb-80b3-5d4bde84bcb3.PNG)
https://eu-citizen.science/blog/2021/03/01/eu-citizenscience-will-fund-10-citizen-science-online-training-courses/

**Comment by frasanz** [comment]
Closing as we are grouping all phone lookandfeel issues in #604
