### ISSUE TITLE
Android version - Language button: Only some languages are visible

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#597]
![imagen15](https://user-images.githubusercontent.com/82102786/114708982-5380bd80-9d2c-11eb-893a-dc7fd7b768ca.PNG)
Only the first languages can be seen and selected in horizontal view, the others are cut off because it is not possible to scroll down in the top menu. I think it would be best to position this button outside of the new foldout menu.

**Comment by frasanz** [comment]
Closing as we are grouping all phone lookandfeel issues in #604
