### ISSUE TITLE
Android version - Add: Add button is cut off

### ISSUE THREAD

**Issue by alimomu** [Ibercivis/EU-CS_platform#598]
![imagen16](https://user-images.githubusercontent.com/82102786/114709670-2ed91580-9d2d-11eb-9fe6-251a711f6029.PNG)

At least on the tablet I am using, the add button is cut off at the bottom of the menu in horizontal view and it is not possible to scroll down within the menu

**Comment by frasanz** [comment]
Closing as we are grouping all phone lookandfeel in #604
