### ISSUE TITLE
 Forum: CSS max-width on images in forum

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#602]
I think the images on the forum need a max-width: 100%; in CSS so they are auto-fitted in the width.
Example: https://eu-citizen.science/forum/forum/introduce-yourself-24/topic/hi-from-the-spotteron-citizen-science-app-platform-32/
Browser: Vivaldi (Chromium based), Win10

**Comment by frasanz** [comment]
Forum is going to be deleted?
