### ISSUE TITLE
Community building & landing page

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#621]
- [ ] weekly news section that changes regularly with a picture or pic+caption
- [ ] landing page different from the resources/projects page -->
- [ ] landing page: integrate ideas so users keep clicking, find 1-2 lines on the project/what is the platform (+ add a "learn more")
- [ ] landing page: present information graphically “prepared” so it is nice to read and look at
- [ ] landing page: randomly change the things to be shown in rotation

**Comment by josircg** [comment]
Hi Claudia, we've already implemented that on our platform. Take a look:

https://civis.ibict.br/

**Comment by frasanz** [comment]
Done in last release, closing this issue
