### ISSUE TITLE
Suggestions from interviews with partners

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#622]
- [ ] Forum: see all the people who joined the group, that gives the feeling to be a group. (topic/thread in the forum)
- [ ] Forum: provide a monthly digest of the posts that are on the forum (automatically generated) – so people just click on their e-mail to go to the forum --> to integrate with the digest in planning
- [ ] Forum: actively start sub-groups of different interests (e.g. on a European wide flora- and fauna-database linked to citizen science activities, comparable to the Netherlands).
- [ ] Landing page: have a feature explaining users how to sign up, how to add new organisations, how to upload projects and resources to be found on the homepage.
- [ ] For policy-makers: show win-win cases for impact on policy makers, where CS in collaboration with policy makers had both benefits? Are there good things out there at a municipality level, at a regional level? Can this be transferred?
- [ ] Improvement: Provide access to content of the platform via “topics”
- [ ] Improvement: Think about use-cases, e.g. I am a citizen scientist and would like to start a project: what should I do and what avoid? I am a citizen scientist and need to work online now: Are there electronic collaboration tools and which are available and tested? For which number of people?

**Comment by jbarbaborderias** [comment]
Noted. (Previous we have to discuss whether maintaining the forum still makes sense)
