### ISSUE TITLE
Blog: all improvements

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#623]
- [ ] improve the blog posting from the admin side: it is really difficult to put any layout at the moment
- [ ] would it be possible to either add labels/categories to blog posts?
- [ ] or even better – create a search field/function that also considers the text of the article (there is no way right now to find articles on inclusion, for example)
- [ ] add an explanation on the blog site would be good to know who can contribute to it and how (and how the blog site works - who can comment?)
- [ ] idea for the sustainability of blog posts here: https://watermining.eu/news/

**Comment by frasanz** [comment]
Adding as possible improvements for the next iteration,
