### ISSUE TITLE
Moderation of organisation profiles

### ISSUE THREAD

**Issue by claudiafabo** [Ibercivis/EU-CS_platform#630]
An email is sent out to the person moderating when a new organisation is added. To make this easier, the automatic email should contain the link to said organisation as otherwise one has to check which one was added last.

This is the email I refer to:
"Thank you for submitting your organisation profile. This profile will now be visible on the platform, and you can make updates or changes to this resource profile at any time, by going to the My Organisations section in your Personal Area (see the top-right of the platform menu).!

**Comment by jbarbaborderias** [comment]
Solved
