### ISSUE TITLE
Profile form Interest Areas field  "results can not be loaded"

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#651]
In my personal profile in editing mode, I'm not able to add words to the 'Interest Areas' field... if I type a whole word it says "the results can not be loaded" . Sometimes if I type one or two characters I get a suggestion list, but then I can't select from it, and if I continue typing the word shown in the suggestion list, it once agains says 'can not be loaded'

**Comment by jbarbaborderias** [comment]
Solved
