### ISSUE TITLE
Introduce a 'gold' colour for the Gold Star Selection page

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#652]
On https://eu-citizen.science/curated/ take the orangey-gold from the Members version of the ECSA logo to use for the word "Selection" on this page, and any other indicators that it is a gold star / curated selection (such as the star itself).

logo colours here: https://ecsa.citizen-science.net/wp-content/uploads/2020/03/ecsa_main_Member.png

**Comment by frasanz** [comment]
Not planned as we will redisgn
