### ISSUE TITLE
stronger shadow line around project/resource tiles

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#653]
some of the profile images uploaded are white or have a white surrounding area, making them not stand out as well in the tiles view - make the line slightly darker or the shadow higher contras
<img width="1163" alt="higher contrast tile line:shadow" src="https://user-images.githubusercontent.com/1629708/139029870-a28149be-dd15-4e00-959d-760e117c7e27.png">
t

**Comment by frasanz** [comment]
We will re-design the complete platform
