### ISSUE TITLE
Cannot access PDF on Citizen Science, An Introduction

### ISSUE THREAD

**Issue by chostett** [Ibercivis/EU-CS_platform#714]
**Describe the bug**
On **Citizen Science, An Introduction,** cannot download the following report:
Bonney et al. 2014. Next Steps for Citizen Science. Science, 343(6178), 1436–1437. 

**To Reproduce**
1. Go to **Citizen Science, An Introduction**
2. Click on "Go to Training"
3. Scroll down to PDF Bonney et al. 2014. Next Steps for Citizen Science. Science, 343(6178), 1436–1437. 
4. Click "Download it here"
5. See error

**Expected behavior**
Expected to download the report.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Ventura 13.5
 - Browser: Firefox 117.0.1, then Safari  16.6
 - Version: see above

**Additional context**

**Comment by frasanz** [comment]
Thanks, @chostett. Once you click on “Go to training,” you are redirected outside of the eu-citizen.science platform, so we are unable to control the behavior of that page. Closing this issue.
