### ISSUE TITLE
new map loses info when zooming in

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#717]
When opening the map on the new release, if I zoom in to my area of the Netherlands I lose all map information and only see the pins - the rest is blank. I had expected to also see the map information in greater detail (as one would with Open Street Map for example). Without that information the map doesn't have value.

**Comment by jbarbaborderias** [comment]
The Tile that the map is using is ‘minimalist’, so it only includes the borders of the countries. It is not really a loss of information, so this cannot be considered a bug.
