### ISSUE TITLE
on new release, profile stays pinned to home page when logged in

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#718]
When I log-in, my profile stays ‘pinned’ at the top of the frontpage, and I have to scroll down to see the rest of the front page.

This is not a nice user experience to always see my own bio at the top of the home page.

(MacBook Air - Chrome Browser)

**Comment by frasanz** [comment]
Noted and changed (very soon in production). Thanks @MobileMaggie
