### ISSUE TITLE
Translation page isn't working

### ISSUE THREAD

**Issue by ajcanepa** [Ibercivis/EU-CS_platform#720]
I have tryied to translate the page from observation.org (__here__: [https://eu-citizen.science/translateProject/68](https://eu-citizen.science/translateProject/68))

But I found an error message
![image](https://github.com/Ibercivis/EU-CS_platform/assets/10628672/2d881d26-12a7-48e9-bb8f-a98317def582)

**Comment by frasanz** [comment]
“@ajcanepa, this issue was resolved in the latest release. You can now add languages when submitting your projects, resources, etc.“​

<img width="809" alt="image" src="https://github.com/user-attachments/assets/1154828b-a140-4f98-9af8-0fb983bc7cd8">
