### ISSUE TITLE
Event edits do not work

### ISSUE THREAD

**Issue by saradorato** [Ibercivis/EU-CS_platform#721]
**To Reproduce**
Server Error (500)
We're sorry, but something went wrong. We're working to fix the issue as soon as possible

**Expected behavior**
I need to edit the information of the events I have submitted

**Screenshots**

**Desktop (please complete the following information):**
Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by frasanz** [comment]
Solved!, thanks @saradorato
