### ISSUE TITLE
Forgot Password? Remember me

### ISSUE THREAD

**Issue by l8wt** [Ibercivis/EU-CS_platform#723]
**Describe the bug**
When filled in the e-mailaddress and push "reset password" I get

"Server Error (500)
We're sorry, but something went wrong. We're working to fix the issue as soon as possible."

**To Reproduce**
1. Go to '(https://eu-citizen.science/login/)'
2. Click on '[Remember me](https://eu-citizen.science/password-reset/)'
3. put in the email adress and push "reset password"'....'https://eu-citizen.science/password-reset/

**Expected behavior**
A confirmation mail and link to change password

**Screenshots**
<img width="1068" alt="Skärmavbild 2024-08-29 kl  13 46 50" src="https://github.com/user-attachments/assets/52c325b1-9cbd-4889-95e9-d0c2cbffbc26">

**Desktop (please complete the following information):**
 - OS: [13.6 (22G120)]
 - Browser [chrome]
 - Version [128.0.6613.84 ]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by frasanz** [comment]
Thanks @l8wt . It was solved and uploading to production very soon.
