### ISSUE TITLE
Various Usability Issues (from 10.03.2020 version)

### ISSUE THREAD

**Issue by jsprinks-ew** [Ibercivis/EU-CS_platform#98]
•	Functionality specification?
•	Content check?
•	Project page images poor resolution
•	Map needs to zoom in to location (no point having the whole world if you are one location)
•	Project page, why are some of the EU-Citizen.Science logos coloured, and some aren't?
•	Language: If I select Spanish for instance, yes the paper title is in Spanish, but everything else is still in English?
•	Profile page - map doesn't seem to do anything, nor does interest areas...
•	If I am told I need to enter more information on 'add a project' page, it deletes my keywords and I need to enter them again.
•	Resources page - when you click 'download' it doesn't download - but takes you to a pdf page. Maybe needs re-labelling.

•	Need some information on what the site actually is on landing page
•	Is the font an accessible one? Seems hard to read...
•	None of the social network links function
•	Keyword search not optimised
•	Resources page perhaps need sorting into categories, or some sort of colour coding
•	'About' page is very bland, looks like a paper abstract. Needs to be looked at.
•	No GDPR / data information when I sign up?
•	No contact information?
•	Add new project: topics missing. What does host mean? Entering long and lat is a very poor way of getting location.

•	Very white, not sure the font is readable enough...

**Comment by frasanz** [comment]
Thanks for your feedback, very usefull, some of the issues your identifies were in our list, creating new issues for others. I'm closing this issue, please re-open if not happy with the solution:

• Project page images poor resolution -> https://github.com/Ibercivis/EU-CS_platform/issues/99 https://github.com/Ibercivis/EU-CS_platform/issues/89
• Map needs to zoom in to location (no point having the whole world if you are one location) -> https://github.com/Ibercivis/EU-CS_platform/issues/100
• Profile page - map doesn't seem to do anything, nor does interest areas... -> https://github.com/Ibercivis/EU-CS_platform/issues/95
• If I am told I need to enter more information on 'add a project' page, it deletes my keywords and I need to enter them again. -> https://github.com/Ibercivis/EU-CS_platform/issues/89
• Need some information on what the site actually is on landing page -> https://github.com/Ibercivis/EU-CS_platform/issues/101
• Is the font an accessible one? Seems hard to read... -> https://github.com/Ibercivis/EU-CS_platform/issues/42
• None of the social network links function --> https://github.com/Ibercivis/EU-CS_platform/issues/102
• Keyword search not optimized --> https://github.com/Ibercivis/EU-CS_platform/issues/103
• Resources page perhaps need sorting into categories, or some sort of colour coding -> https://github.com/Ibercivis/EU-CS_platform/issues/101
• 'About' page is very bland, looks like a paper abstract. Needs to be looked at. -> https://github.com/Ibercivis/EU-CS_platform/issues/101
• No GDPR / data information when I sign up? -> https://github.com/Ibercivis/EU-CS_platform/issues/104 -> https://github.com/Ibercivis/EU-CS_platform/issues/80
• Add new project:  What does host mean?  -> https://github.com/Ibercivis/EU-CS_platform/issues/95
Entering long and lat is a very poor way of getting location. -> https://github.com/Ibercivis/EU-CS_platform/issues/105

----
• Content check? -> As it is not an specific technical issue, removing it, although we know that the content must be revised and improved

• Language: If I select Spanish for instance, yes the paper title is in Spanish, but everything else is still in English? - Providing translation in the second release

• Resources page - when you click 'download' it doesn't download - but takes you to a pdf page. Maybe needs re-labelling.  (Thinking on it, you know that reading in the navigator / downloding depends on the navigation configuration), maybe rename is the best option.
• Add new project: topics missing (It is working for me, can you confirm it's not working?)
